navikt/k9-sak-web

- packages/fakta-beregning/src/components/avklareAktiviteter/AvklareAktiviteterPanel.spec.jsx
- packages/fakta-beregning/src/components/fellesFaktaForATFLogSN/InntektFieldArrayRow.spec.jsx
- packages/fakta-fordel-beregningsgrunnlag/src/components/FordelingHelpText.spec.jsx
- packages/fakta-omsorgen-for/i18n/intl-enzyme-test-helper-fakta-omsorgen-for.js
- packages/fakta-omsorgen-for/src/OmsorgenForFaktaIndex.tsx
- packages/fakta-omsorgen-for/src/components/SokerinfoTable.spec.jsx
- packages/fakta-omsorgen-for/src/components/omsorgenForInfo.less
- packages/storybook/.storybook/config.js
- packages/storybook/stories/fakta/pleiepenger/OmsorgenForInfoPanel.stories.tsx
- [] Ja
- [] Nei
- [] Ja
- [] Nei
> Fakta alder omsorg storybook og test

- docker-compose.yml
- package.json
Endrer docker image navn fra k9-sak-frontend da det allerede eksisterer på fpsak-frontend
> endrer docker image navn

- package.json
- packages/fakta-omsorgen-for/src/components/SokerinfoTable.tsx
- packages/storybook/.storybook/webpack.config.js
- webpack/webpack.common.dev_and_prod.js
- yarn.lock
- [] Ja
- [] Nei
- [] Ja
- [] Nei
> fjerner svgr foreløpig da det ikke funket med tester

- packages/sak-historikk/src/components/maler/HistorikkMalType10.jsx
- packages/sak-historikk/src/components/maler/HistorikkMalType6.jsx
- packages/sak-historikk/src/components/maler/HistorikkMalType7.jsx
- packages/sak-historikk/src/components/maler/HistorikkMalType8.jsx
- packages/sak-historikk/src/components/maler/HistorikkMalType9.jsx
- packages/sak-historikk/src/components/maler/HistorikkMalTypeFeilutbetaling.jsx
- packages/sak-historikk/src/components/maler/historikkMalType2.jsx
- packages/sak-historikk/src/components/maler/historikkMalType3.jsx
- packages/sak-historikk/src/components/maler/historikkMalType5.jsx
- [] Ja
- [] Nei
- [] Ja
- [] Nei
> bruker useIntl hook istedenfor HOC

- packages/fakta-medisinsk-vilkar/src/components/InnlagtBarnRadio.tsx
- packages/fakta-medisinsk-vilkar/src/components/MedisinskVilkarForm.tsx
- packages/fakta-medisinsk-vilkar/src/components/OmsorgspersonerRadio.tsx
- [] Ja
- [] Nei
- [] Ja
- [] Nei
> fjernet ubrukte props

- packages/types/index.jsx
- packages/types/package.json
- packages/types/src/kodeverk.ts
- packages/types/src/totrinnskontroll/Aktivitet.ts
- packages/types/src/totrinnskontroll/Approval.ts
- packages/types/src/totrinnskontroll/ArbeidsforholdDto.ts
- packages/types/src/totrinnskontroll/BehandlingKlageVurdering.ts
- packages/types/src/totrinnskontroll/BehandlingStatusType.ts
- packages/types/src/totrinnskontroll/Behandlingsresultat.ts
- packages/types/src/totrinnskontroll/KlageVurderingResultat.ts
- packages/types/src/totrinnskontroll/SkjermlenkeType.ts
- packages/types/src/totrinnskontroll/TotrinnskontrollAksjonspunkter.ts
- packages/types/src/totrinnskontroll/Uttak.ts
- tsconfig.json
- [] Ja
- [] Nei
- [] Ja
- [] Nei
> laget pakke for felles interfacer

- packages/fp-felles/src/eksterneLenker.jsx
Siden er p.t. ikke tilgjengelig, men er meldt og vil åpnes.
> Endrer eksternlenke på systemrutine til K9-sak

- packages/fakta-medisinsk-vilkar/src/components/KontinuerligTilsynOgPleie.tsx
- packages/fakta-medisinsk-vilkar/src/components/MedisinskVilkarUtils.spec.ts
- packages/fakta-medisinsk-vilkar/src/components/MedisinskVilkarUtils.ts
- packages/fakta-medisinsk-vilkar/src/components/Tilsynsperioder.tsx
forbedret rendring av tilsynsperioder, gjort på "riktig" måte nå
> laget hjelpefunksjon for datoer pga console warnings fra moment.js

- packages/behandling-felles/index.tsx
- packages/behandling-felles/src/components/SideMenuWrapper.spec.tsx
- packages/behandling-felles/src/components/SideMenuWrapper.tsx
- packages/behandling-pleiepenger/src/components/PleiepengerFakta.spec.tsx
- packages/behandling-pleiepenger/src/components/PleiepengerFakta.tsx
- packages/behandling-tilbakekreving/src/components/TilbakekrevingFakta.tsx
- public/sprak/nb_NO.json
Also changes label from "Fakta om" to "Saksopplysninger"
> Rename FaktaPanel to SideMenuWrapper

- packages/behandling-pleiepenger/src/BehandlingPleiepengerIndex.tsx
- packages/behandling-pleiepenger/src/data/pleiepengerBehandlingApi.jsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPleiepengerPanelDefinisjoner.tsx
- packages/fakta-arbeidsforhold/src/components/arbeidsforholdDetaljer/ArbeidsforholdRadioknapper.jsx
- packages/fakta-arbeidsforhold/src/components/arbeidsforholdDetaljer/ArbeidsforholdRadioknapper.spec.jsx
- packages/fakta-arbeidsforhold/src/components/arbeidsforholdDetaljer/PersonAksjonspunktText.spec.jsx
- packages/fakta-arbeidsforhold/src/propTypes/arbeidsforholdPropType.jsx
- packages/prosess-vedtak/src/VedtakProsessIndex.jsx
- packages/prosess-vedtak/src/components/VedtakForm.jsx
- packages/prosess-vedtak/src/components/VedtakForm.spec.jsx
- packages/prosess-vedtak/src/components/VedtakPanels.jsx
- packages/sak-app/src/fagsak/FagsakIndex.jsx
- packages/sak-visittkort/src/components/VisittkortPanel.spec.jsx
- packages/sak-visittkort/src/components/VisittkortPanel.tsx
- public/sprak/nb_NO.json
endret navn på prosessteg medisinsk vilkår til sykdom
fjernet kall mot endepunkter vi ikke trenger
> tilpasset for ny vedtaksstruktur backend

- packages/fakta-medisinsk-vilkar/i18n/nb_NO.json
- packages/fakta-medisinsk-vilkar/src/components/Tilsynsperioder.tsx
- packages/fakta-medisinsk-vilkar/src/components/diagnosekodeSelector.less
- packages/form/src/PeriodpickerField.tsx
- packages/shared-components/src/periodpicker/Periodpicker.jsx
- packages/shared-components/src/periodpicker/periodpicker.less
> mulig å rendre kalender-overlay oppover

- packages/fakta-medisinsk-vilkar/src/components/KontinuerligTilsynOgPleie.tsx
- packages/fakta-medisinsk-vilkar/src/components/MedisinskVilkarForm.tsx
- packages/fakta-medisinsk-vilkar/src/components/MedisinskVilkarUtils.spec.ts
- packages/fakta-medisinsk-vilkar/src/components/MedisinskVilkarUtils.ts
- packages/fakta-medisinsk-vilkar/src/components/Tilsynsperioder.tsx
- packages/fakta-medisinsk-vilkar/src/types/MedisinskVilkårValues.ts
- packages/types/src/medisinsk-vilkår/MedisinskVilkår.ts
- packages/types/src/medisinsk-vilkår/MedisinskVilkårConstants.ts
rettet formattering i knapp som bruker periodedato
> mapping av årsakssammenheng

- packages/behandling-omsorgspenger/index.tsx
- packages/behandling-omsorgspenger/package.json
- packages/behandling-omsorgspenger/src/BehandlingOmsorgspengerIndex.tsx
- packages/behandling-omsorgspenger/src/components/OmsorgspengerFakta.spec.tsx
- packages/behandling-omsorgspenger/src/components/OmsorgspengerFakta.tsx
- packages/behandling-omsorgspenger/src/components/OmsorgspengerPaneler.tsx
- packages/behandling-omsorgspenger/src/components/OmsorgspengerProsess.spec.tsx
- packages/behandling-omsorgspenger/src/components/OmsorgspengerProsess.tsx
- packages/behandling-omsorgspenger/src/data/omsorgspengerBehandlingApi.jsx
- packages/behandling-omsorgspenger/src/panelDefinisjoner/faktaOmsorgspengerPanelDefinisjoner.spec.tsx
- packages/behandling-omsorgspenger/src/panelDefinisjoner/faktaOmsorgspengerPanelDefinisjoner.tsx
- packages/behandling-omsorgspenger/src/panelDefinisjoner/prosessStegOmsorgspengerPanelDefinisjoner.tsx
- packages/behandling-omsorgspenger/src/panelDefinisjoner/vedtakStatusUtlederOmsorgspenger.ts
- packages/behandling-omsorgspenger/src/types/fetchedDataTsType.ts
- packages/behandling-pleiepenger/src/components/PleiepengerFakta.spec.tsx
- packages/behandling-pleiepenger/src/components/PleiepengerProsess.spec.tsx
- packages/sak-app/package.json
- packages/sak-app/src/behandling/BehandlingIndex.jsx
- yarn.lock
Copied from behandling-pleiepenger. Renamed modules to Omsorgspenger and removed Pleiepenger-specific panels/process-steps
> Add behandling-omsorgspenger package

- deploy/dev-fss.yml
- packages/behandling-felles/src/definisjon/byggProsessmenySteg.tsx
- packages/behandling-klage/src/data/klageBehandlingApi.ts
- packages/behandling-klage/src/definition/klageStegDefinition.ts
- packages/fp-felles/src/featureToggle.jsx
- packages/prosess-formkrav/src/components/FormkravKlageFormNfp.jsx
- packages/prosess-vedtak-klage/src/components/VedtakKlageForm.jsx
- packages/sak-app/src/app/duck.jsx
- packages/sak-app/src/behandling/ApplicationContextPath.jsx
- packages/sak-app/src/behandling/selectors/behandlingerSelectors.jsx
- packages/sak-app/src/behandlingmenu/duck.jsx
- packages/sak-app/src/behandlingsupport/history/HistoryIndex.jsx
- packages/sak-app/src/data/fpsakApi.jsx
- packages/sak-app/src/fagsak/duck.jsx
- packages/sak-app/src/fagsakprofile/FagsakProfileIndex.jsx
- packages/sak-app/src/kodeverk/duck.jsx
- packages/sak-dekorator/i18n/nb_NO.json
- public/sprak/nb_NO.json
- webpack/mocks/feature-toggles.js
- webpack/webpack.dev.server.js
Legger til rette for kommunikasjon med ny klageapplikasjon.
> Integrerer mot k9-klage

- packages/behandling-omsorgspenger/src/components/OmsorgspengerFakta.spec.tsx
- packages/behandling-omsorgspenger/src/panelDefinisjoner/faktaOmsorgspengerPanelDefinisjoner.tsx
Legger til paneler når de er klare
> TSF-293 Fjerner uttak fra sidepanel da det gjelder pleiepenger

- packages/sak-meny/src/components/createNewBehandling/CreateNewBehandlingModal.jsx
La til aktørid i spørringen fordi klageløsningen trenger det. Har nå lagt inn en sjekk som gjør at denne _kun_ kommer på spørringer til klageløsningen.
> Sender aktørid bare til klage

- packages/fakta-opptjening-oms/src/OpptjeningFaktaIndex.tsx
- packages/fakta-opptjening-oms/src/components/OpptjeningFaktaForm.tsx
- packages/fakta-opptjening-oms/src/components/opptjeningFaktaForm.less
> rettet feil navn i prop

- packages/fakta-opplysninger-fra-soknaden/src/FrilanserForm.tsx
- packages/fakta-opplysninger-fra-soknaden/src/SelvstendigNæringsdrivendeForm.tsx
- packages/storybook/stories/fakta/OpplysningerFraSoknaden.stories.tsx
laget story for opplysninger fra soknaden
> la på validering for antall siffer i inntekt

- packages/fakta-opplysninger-fra-soknaden/src/OpplysningerFraSoknadenForm.tsx
Fix disabled-bug on submit-button
Show Frilans-section only when relevant
Fix lock/unlock form logic
> A few bugfixes

- packages/fakta-opplysninger-fra-soknaden/src/FrilanserForm.tsx
- packages/fakta-opplysninger-fra-soknaden/src/OpplysningerFraSoknadenForm.tsx
- packages/fakta-opplysninger-fra-soknaden/src/SelvstendigNæringsdrivendeForm.tsx
- packages/fakta-opplysninger-fra-soknaden/src/types/OpplysningerFraSoknadenTypes.ts
- packages/storybook/stories/fakta/OpplysningerFraSoknaden.stories.tsx
SelvstendigNæringsdrivendeForm og FrilanserForm baserte seg på feil verdier for å vise inntekt
for SSN i frilans og frilans i SSN søknadsperiode
> Overstyring frilanssøknad bugfix

- packages/fakta-opplysninger-fra-soknaden/src/OpplysningerFraSoknadenForm.tsx
Retter også noe på eksisterende logikk i lagPeriodeForOppgittEgenNæringFørSøkerperioden, og gjort
koden mer lesbar.
> Fikser ".... of undefined"-feil på iSøkerPerioden.oppgittEgenNæring

- packages/behandling-omsorgspenger/src/panelDefinisjoner/prosessStegOmsorgspengerPanelDefinisjoner.tsx
- packages/prosess-tilkjent-ytelse/src/components/TilkjentYtelse.jsx
Lagt til avslagshåndtering i tilkjent ytelse på omsorgspenger. Manglet håndtering av tilfellene hvor
man mottar en liste med perioder, men ikke har noen andeler.
> Manglende avslagshåndtering

- packages/fakta-opptjening-oms/src/components/OpptjeningFaktaForm.tsx
- packages/fakta-opptjening-oms/src/components/OpptjeningInfoPanel.tsx
La på manglende tilstandshåndtering av faktapanelet for opptjening for når
man ikke har noen opptjeningsaktiviteter ennå.
> Tilstandshåndtering OpptjeningFakta

- packages/behandling-omsorgspenger/src/BehandlingOmsorgspengerIndex.tsx
- packages/behandling-omsorgspenger/src/data/omsorgspengerBehandlingApi.jsx
- packages/behandling-omsorgspenger/src/panelDefinisjoner/prosessStegOmsorgspengerPanelDefinisjoner.tsx
- packages/prosess-aarskvantum-oms/i18n/nb_NO.json
- packages/prosess-aarskvantum-oms/package.json
- packages/prosess-aarskvantum-oms/src/components/AksjonspunktForm.tsx
- packages/prosess-aarskvantum-oms/src/components/Uttaksplan.spec.tsx
- packages/prosess-aarskvantum-oms/src/components/Uttaksplan.tsx
- packages/prosess-aarskvantum-oms/src/ÅrskvantumIndex.spec.tsx
- packages/prosess-aarskvantum-oms/src/ÅrskvantumIndex.tsx
- packages/storybook/stories/omsorgspenger/Uttaksplan.stories.tsx
Tabs for siste uttaksplan og full uttaksplan.
Flytter aksjonspunkt øverst
> Tsf 846/full uttaksplan

- packages/prosess-beregningsgrunnlag/src/components/BeregningsgrunnlagFieldArrayComponent.jsx
- packages/prosess-beregningsgrunnlag/src/components/beregningForm/BeregningForm.jsx
- packages/prosess-beregningsgrunnlag/src/components/beregningForm/BeregningForm.spec.jsx
- packages/prosess-beregningsgrunnlag/src/components/ytelsesspesifikkseOpplysninger/YtelsegrunnlagPanel.jsx
- packages/prosess-beregningsgrunnlag/src/components/ytelsesspesifikkseOpplysninger/frisinn/Beregningsresultat.jsx
- packages/prosess-beregningsgrunnlag/src/components/ytelsesspesifikkseOpplysninger/frisinn/FrisinnUtils.jsx
- packages/prosess-beregningsgrunnlag/src/components/ytelsesspesifikkseOpplysninger/frisinn/FrisinnUtils.spec.jsx
- packages/prosess-beregningsgrunnlag/src/components/ytelsesspesifikkseOpplysninger/frisinn/Frisinnpanel.jsx
- packages/prosess-beregningsgrunnlag/src/components/ytelsesspesifikkseOpplysninger/frisinn/Grenseverdi.jsx
- packages/prosess-beregningsgrunnlag/src/components/ytelsesspesifikkseOpplysninger/frisinn/Grenseverdi.spec.jsx
- packages/prosess-beregningsgrunnlag/src/propTypes/beregningsgrunnlagBehandlingPropType.jsx
grenseverdi komponent og beregningsresultatkomponent
> FIX: Reverter endring som ikke hensyntok forskjellige behov mellom

- packages/prosess-beregningsgrunnlag/src/components/BeregningFP.jsx
- packages/prosess-beregningsgrunnlag/src/components/arbeidstaker/AksjonspunktBehandlerAT.jsx
Beregningsgrunnlag kan komme tilbake som et objekt og ikke en array. Så har lagt inn en sjekk på dette samt sjekk på om det i det hele tatt er der.
> SF-1073 - Legger til NP sjekker på Beregninggrunnlag

- .github/workflows/promote-command.yml
for å se om det derfor deploy feiler
> Negraderer actions/checkout@v1 igjen

- proxy.nginx
Legger til unntak for self på font-src og inline for style og script. åpner også for Sentry
> legger til unntak for inline style, inline script og Sentry i proxy

- proxy.nginx
Legger til img-src i CSP unntak slik at man får lastet inn svg
> Legger til img-src i CSP unntak slik at man får lastet inn svg

- packages/prosess-vedtak/i18n/nb_NO.json
- packages/prosess-vedtak/package.json
- packages/prosess-vedtak/src/components/revurdering/VedtakRedusertUtbetalingArsaker.jsx
- packages/prosess-vedtak/src/components/revurdering/VedtakRedusertUtbetalingArsaker.spec.jsx
- packages/prosess-vedtak/src/components/revurdering/VedtakRevurderingForm.jsx
- packages/prosess-vedtak/src/components/revurdering/VedtakRevurderingSubmitPanel.jsx
- packages/prosess-vedtak/src/components/revurdering/VedtakRevurderingSubmitPanel.spec.jsx
- yarn.lock
Gjør også at sjekkboksene hvor man velger årsaker til redusert utbetaling kun er synlige når utbetaling er redusert.
> Verifiserer årsaker til redusert utbetaling

- deploy/dev-fss-default.yml
- deploy/prod-fss-default.yml
- packages/fakta-medisinsk-vilkar/src/components/DiagnosekodeSelector.tsx
- proxy.nginx
- start-server.sh
- webpack/webpack.dev.server.js
Dette forenkler CORS-oppsett -- særlig i produksjon.
> Legger diagnosekoder bak k9-proxy.

- packages/fakta-fordel-beregningsgrunnlag/src/FordelBeregningsgrunnlagFaktaIndex.jsx
mangler å importere moment
https://sentry.gc.nav.no/nav/k9-sak-web/issues/13234/?query=is%3Aunresolved
> moment is not defined

- packages/fakta-fordel-beregningsgrunnlag/src/FordelBeregningsgrunnlagFaktaIndex.jsx
legger til import { DDMMYYYY_DATE_FORMAT } from '@fpsak-frontend/utils'; da denne manglet også
> Sentry fikser undefined

- packages/sak-app/src/behandlingmenu/BehandlingMenuDataResolver.tsx
- packages/sak-app/src/behandlingmenu/BehandlingMenuIndex.spec.tsx
- packages/sak-app/src/behandlingmenu/BehandlingMenuIndex.tsx
- packages/sak-app/src/behandlingmenu/accessMenu.spec.ts
- packages/sak-app/src/behandlingmenu/accessMenu.ts
Fjerner harSoknad parameter fra accessmenu for nå da det ikke er i bruk i K9 ennå.
> Sett behandling på vent

- packages/sak-app/src/behandlingmenu/accessMenu.spec.ts
- packages/sak-app/src/behandlingmenu/accessMenu.ts
- packages/sak-meny-ny-behandling/src/components/NyBehandlingModal.tsx
Legger til manglende revurderingsårsaker og fjerner noe engangssøknad funskjoner etter fp
> FAGSYSTEM-140507  Feil kategorier ved opprettelse av revurdering

- packages/sak-historikk/src/components/maler/historikkMalType4.jsx
PFP-9604 kopierte endringen fra fp-frontend.Nå historikkMalType4 kan vise spesiell tegn ordentlig
> PFP-9604 kopierte endringen fra fp-frontend.Nå historikkMalType4 kan vise spesiell tegn ordentlig

- packages/behandling-klage/src/BehandlingKlageIndex.tsx
- packages/behandling-klage/src/components/KlageProsess.spec.tsx
- packages/behandling-klage/src/data/klageBehandlingApi.ts
- packages/behandling-klage/src/panelDefinisjoner/prosessStegPaneler/FormKravFamOgPensjonProsessStegPanelDef.tsx
- packages/behandling-klage/src/panelDefinisjoner/prosessStegPaneler/FormKravKlageInstansProsessStegPanelDef.tsx
- packages/behandling-klage/src/types/fetchedDataTsType.ts
- packages/prosess-formkrav/i18n/nb_NO.json
- packages/prosess-formkrav/src/FormkravProsessIndex.jsx
- packages/prosess-formkrav/src/components/FormkravKlageForm.jsx
- packages/prosess-formkrav/src/components/FormkravKlageForm.spec.jsx
- packages/prosess-formkrav/src/components/FormkravKlageFormKa.jsx
- packages/prosess-formkrav/src/components/FormkravKlageFormKa.spec.jsx
- packages/prosess-formkrav/src/components/FormkravKlageFormNfp.jsx
- packages/prosess-formkrav/src/components/FormkravKlageFormNfp.spec.jsx
- packages/sak-totrinnskontroll/src/components/aksjonspunktTekster/aksjonspunktTekstUtleder.spec.tsx
- packages/sak-totrinnskontroll/src/components/aksjonspunktTekster/aksjonspunktTekstUtleder.tsx
- packages/types/src/klageVurderingTsType.ts
Ved kun en klagepart så skal den være valgt på forhånd. Ved flere skal ingen være valgt.
> Valgt klagepart skal ikke være mulig å endre i KA formkrav

- packages/prosess-beregningsgrunnlag/src/components/BeregningFP.jsx
Co-authored-by: Kenneth Koh <kenneth.koh@nav.no>
> Lagt tilbake spread på aksjonspunkt.

- packages/prosess-vilkar-opptjening-oms/i18n/nb_NO.json
- packages/prosess-vilkar-opptjening/i18n/nb_NO.json
Co-authored-by: Kenneth Koh <kenneth.koh@nav.no>
> Endret tekst fra 6 mnd til 28 dagers

- .github/workflows/deploy-docker-image.yml
* bytter til major version for offisielle GHA
> fix: fjerner legacy pipeline til k9-verdikjede kall

- packages/behandling-pleiepenger/src/components/Uttak.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/UttakProsessStegPanelDef.tsx
> sender arbeidsgiverdata til uttak

- packages/sak-dekorator/src/HeaderWithErrorPanel.tsx
- packages/sak-dekorator/src/headerWithErrorPanel.less
* Legger til stygg grønn bakgrunn i test.
* Retter header til div slik at vi ikke har to nøstede header-tager.
> Legger til stygg grønn bakgrunn i test.

- packages/behandling-felles/index.ts
- packages/behandling-felles/src/components/aksjonspunkt-uten-løsning-modal/AksjonspunktUtenLøsningModal.tsx
- packages/behandling-felles/src/components/aksjonspunkt-uten-løsning-modal/aksjonspunktUtenLøsningModal.less
- packages/behandling-felles/src/util/harOpprettetAksjonspunkt.ts
- packages/behandling-pleiepenger/src/components/PleiepengerPaneler.tsx
Made modal for showing message when a certain aksjonspunkt cannot be solved
Applied modal to aksjonspunkt 9203 for PSB
> AksjonspunktUtenLøsningModal

- Dockerfile
- deploy/dev-fss-default.yml
- deploy/prod-fss-default.yml
- proxy.nginx
- start-server.sh
> Reverter read-only fixes

- packages/sak-historikk/src/components/maler/felles/SnakkebobleContainer.tsx
lowercase i lokalt, men ikke i Q og prod
> vise navn på saksbehandler både i prod og lokalt. 

- packages/sak-app/src/behandlingsupport/BehandlingSupportIndex.tsx
- packages/sak-app/src/behandlingsupport/dokument/DokumentIndex.tsx
- packages/sak-dokumenter/src/DokumenterSakIndex.tsx
- packages/sak-dokumenter/src/components/DocumentList.tsx
> henter brukers fnr fra annet sted

- packages/prosess-vilkar-overstyring/i18n/nb_NO.json
- packages/prosess-vilkar-overstyring/src/components/VilkarresultatMedBegrunnelse.tsx
- packages/prosess-vilkar-overstyring/src/components/VilkarresultatMedOverstyringForm.tsx
Reverts navikt/k9-sak-web#3054
> Revert "TSF-2341 - viser begrunnelse for automatisk behandlede vilkår"

- packages/behandling-pleiepenger-sluttfase/i18n/nb_NO.json
- packages/behandling-pleiepenger-sluttfase/src/components/MedisinskVilkår.tsx
- packages/behandling-pleiepenger-sluttfase/src/panelDefinisjoner/faktaPaneler/MedisinskVilkarFaktaPanelDef2.tsx
- packages/behandling-pleiepenger/src/components/MedisinskVilkår.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/faktaPaneler/MedisinskVilkarFaktaPanelDef2.tsx
Reverts navikt/k9-sak-web#3483
> Revert "Revert "Fix/sluttfase justeringer""

- packages/sak-app/src/app/AppIndex.spec.tsx
- packages/sak-app/src/app/AppIndex.tsx
- packages/sak-app/src/app/components/Dekorator.spec.tsx
- packages/sak-app/src/app/components/Dekorator.tsx
- packages/sak-app/src/app/initLinks.ts
- packages/sak-app/src/app/useHentInitLenker.tsx
- packages/sak-dekorator/src/HeaderWithErrorPanel.spec.tsx
- packages/sak-dekorator/src/HeaderWithErrorPanel.tsx
- packages/storybook/stories/sak/DekoratorSakIndex.stories.tsx
Reverts navikt/k9-sak-web#3555
> Nytt forsøk på nye dekoratørlenker

- packages/modal-sett-pa-vent/src/components/SettPaVentModal.spec.tsx
- packages/modal-sett-pa-vent/src/components/SettPaVentModal.tsx
- packages/modal-sett-pa-vent/src/components/settPaVentModal.less
Endrer logikk for inntenktsmeldingmodal
> Legger inn lukknapp for modal

- packages/sak-app/src/app/AppIndex.tsx
- packages/sak-app/src/app/components/Dekorator.spec.tsx
- packages/sak-app/src/app/components/Dekorator.tsx
- packages/sak-app/src/app/initLinks.ts
- packages/sak-app/src/app/useHentInitLenker.tsx
- packages/sak-dekorator/src/HeaderWithErrorPanel.spec.tsx
- packages/sak-dekorator/src/HeaderWithErrorPanel.tsx
- packages/storybook/stories/sak/DekoratorSakIndex.stories.tsx
Reverts navikt/k9-sak-web#3557
> Revert "Nytt forsøk på nye dekoratørlenker"

- .github/workflows/deploy-docker-image.yml
- .github/workflows/promote-command.yml
- .github/workflows/valid-pull-request.yml
Reverts navikt/k9-sak-web#3277
> Revert "Bump actions/checkout from 2 to 3"

- .github/workflows/valid-pull-request.yml
- package.json
- webpack/common/module.ts
- webpack/common/plugins.ts
- webpack/constants.ts
- webpack/webpack.dev.ts
- yarn.lock
Endret source-map config
Sjekker etter circular deps i prodbygg
> Gjør bygget raskere

- .github/workflows/valid-pull-request.yml
- .gitignore
- package.json
- webpack/common/plugins.ts
- webpack/webpack.dev.ts
- webpack/webpack.prod.ts
Og at de sjekkes for circular dependencies
> Kjører devbygg i Github actions da formålet er å se om bygget kjører

- deploy/dev-fss-k9saksbehandling.yml
- packages/form/index.jsx
- packages/form/src/CheckboxGroupFormik.tsx
- packages/form/src/formikUtils.js
- packages/prosess-vedtak/i18n/nb_NO.json
- packages/prosess-vedtak/src/components/PreviewLink.tsx
- packages/prosess-vedtak/src/components/SakGårIkkeTilBeslutterModal.tsx
- packages/prosess-vedtak/src/components/VedtakSubmit.tsx
- packages/prosess-vedtak/src/components/brev/InformasjonsbehovAutomatiskVedtaksbrev.tsx
- packages/prosess-vedtak/src/components/revurdering/VedtakRevurderingSubmitPanel.tsx
Ny wrapper for CheckboxGroup med Formik
Setter type på flere knapper
> TSF-2710 - fikser valideringen av checkbox

- packages/prosess-vilkar-soknadsfrist/src/components/SoknadsfristVilkarForm.tsx
> Fiks for fler perioder/delte perioder

- packages/prosess-vilkar-soknadsfrist/src/SoknadsfristVilkarProsessIndex.tsx
- packages/prosess-vilkar-soknadsfrist/src/components/SoknadsfristVilkarDokument.tsx
- packages/prosess-vilkar-soknadsfrist/src/components/SoknadsfristVilkarForm.spec.tsx
- packages/prosess-vilkar-soknadsfrist/src/components/SoknadsfristVilkarForm.tsx
Reverts navikt/k9-sak-web#3909
> Revert "Endrer fra alle dokumenter til dokumenter i aktiv periode"

- packages/prosess-vilkar-soknadsfrist/src/SoknadsfristVilkarProsessIndex.tsx
- packages/prosess-vilkar-soknadsfrist/src/components/SoknadsfristVilkarDokument.tsx
- packages/prosess-vilkar-soknadsfrist/src/components/SoknadsfristVilkarForm.spec.tsx
- packages/prosess-vilkar-soknadsfrist/src/components/SoknadsfristVilkarForm.tsx
Reverts navikt/k9-sak-web#3911
> Endrer fra alle dokumenter til dokumenter i aktiv periode

- packages/form/src/SelectFieldFormik.tsx
- packages/prosess-vedtak/src/components/FritekstBrevPanel.tsx
- packages/prosess-vedtak/src/components/VedtakForm.tsx
- packages/prosess-vedtak/src/components/brev/BrevPanel.tsx
- packages/prosess-vedtak/src/components/brev/InformasjonsbehovAutomatiskVedtaksbrev.tsx
> Flere forbedringer i vedtak

- deploy/prod-fss-k9saksbehandling.yml
Fjernet slash i slutet på URL, konflikt med nyere versjon av ktor.
> Endring diagnosekode-api-URL prod

- deploy/dev-fss-k9saksbehandling.yml
- deploy/prod-fss-k9saksbehandling.yml
- feature-toggles.json
- packages/prosess-vilkar-soknadsfrist/src/components/SoknadsfristVilkarDokument.tsx
- webpack/mocks/feature-toggles.js
- yarn.lock
> TSF-2738 - Fiks for begrensing av kalender

- packages/sak-dokumenter/src/components/DocumentList.spec.tsx
- packages/sak-dokumenter/src/components/DocumentList.tsx
- packages/sak-dokumenter/src/components/documentList.less
Gammel løsning gjorde at fokus endret seg ved midtklikk også
> TSF-2582 - Endrer klikkhåndtering i dokumentliste

- deploy/dev-fss-k9saksbehandling.yml
- package.json
- packages/sak-app/src/fagsak/FagsakIndex.tsx
- packages/sak-behandling-velger/package.json
- packages/sak-behandling-velger/src/BehandlingVelgerSakIndex.tsx
- packages/sak-behandling-velger/src/components/BehandlingPicker.spec.tsx
- packages/sak-behandling-velger/src/components/BehandlingPicker.tsx
- packages/sak-behandling-velger/src/components/behandlingVelgerUtils.tsx
- packages/storybook/stories/sak/BehandlingVelgerSakIndexOld.stories.tsx
- yarn.lock
Bruker react-query for caching av data
> Begrenser antall behandlinger som hentes av gangen

- packages/rest-api/src/requestApi/RequestRunner.ts
- packages/sak-app/src/app/AppIndex.tsx
- packages/sak-app/src/app/components/Home.tsx
> Popupvindu som lar bruker logge inn igjen ved 401

- packages/sak-infosider/src/UnauthorizedPage.tsx
Gjør at popupen for innlogging kommer frem igjen
> Refresh siden ved navigering til innloggingssiden

- packages/behandling-frisinn/src/components/FrisinnProsess.tsx
- packages/behandling-omsorgspenger/src/components/OmsorgspengerProsess.tsx
- packages/behandling-opplaeringspenger/src/components/OpplaeringspengerProsess.tsx
- packages/behandling-pleiepenger-sluttfase/src/components/PleiepengerSluttfaseProsess.tsx
- packages/behandling-pleiepenger/src/components/PleiepengerProsess.tsx
- packages/behandling-unntak/src/components/UnntakProsess.tsx
- packages/behandling-utvidet-rett/src/components/UtvidetRettProsess.tsx
- packages/prosess-vedtak/src/components/VedtakForm.tsx
- packages/prosess-vedtak/src/components/VedtakSubmit.tsx
- packages/prosess-vedtak/src/components/brev/BrevPanel.spec.jsx
- packages/prosess-vedtak/src/components/brev/BrevPanel.tsx
- packages/prosess-vedtak/src/components/revurdering/VedtakRevurderingSubmitPanel.tsx
- packages/sak-app/src/data/useVisForhandsvisningAvMelding.tsx
- packages/utils/src/formidlingUtils.tsx
Reverts navikt/k9-sak-web#4440
> Revert "Forhindre at automatisk brev feiler"

- packages/prosess-vedtak/src/components/FritekstRedigering/FritekstRedigering.tsx
- packages/prosess-vedtak/src/components/FritekstRedigering/RedigeringUtils.ts
Endret slik at suffiks kun henter elementer etter siste redigerbare felt.
Tilpasser ny section i [pdfgen](https://github.com/navikt/k9-pdfgen-psb/blob/089f8f7c6e64846f302176d9ecdde966c26f0bbf/templates/felles/base.hbs#L29)
> Endret querySelector for å hente ut redigerbart felt etter at det ble flyttet ett nivå ned fra body

- packages/utils/src/hentAktivePerioderFraVilkar.ts
Reverts navikt/k9-sak-web#4533
> Revert "Oppdater logikk for filtrering av perioder i søknadsfrist"

- packages/prosess-vedtak/i18n/nb_NO.json
- packages/prosess-vedtak/src/components/FritekstRedigering/FritekstEditor.tsx
- packages/shared-components/index.ts
- packages/shared-components/src/apneSakINyttVinduKnapp/ÅpneSakINyttVinduKnapp.tsx
Mulighet for å åpne sak i nytt vindu fra brev-editor. Mulig til bruk andre steder i løsningen og.
> Nytt vindu

- packages/prosess-vedtak/src/components/FritekstRedigering/FritekstEditor.tsx
> Fjerne use-effect

- packages/prosess-vedtak/src/components/FritekstBrevPanel.tsx
- packages/prosess-vedtak/src/components/FritekstRedigering/FritekstEditor.tsx
- packages/prosess-vedtak/src/components/FritekstRedigering/FritekstRedigering.tsx
- packages/prosess-vedtak/src/components/PreviewLink.tsx
- packages/prosess-vedtak/src/components/brev/BrevPanel.tsx
Lagrer ikke brev dersom read only
> Disabler forhåndsvisning knapp til data er på plass

- packages/behandling-felles/src/components/sideMenuWrapper.module.css
- packages/behandling-utvidet-rett/package.json
- packages/prosess-aarskvantum-oms/package.json
- packages/sak-app/package.json
- yarn.lock
> bump omsorgsdager

- packages/rest-api-hooks/src/RestApiState.ts
- packages/sak-app/src/behandlingsupport/historikk/HistorikkIndex.tsx
- packages/sak-app/src/fagsak/FagsakIndex.tsx
This reverts commit ccf5a0c430ce656046fe2f59987f0ea5255d0e3c.
> Revert "Unngå doble serverkall pga <LoadingPanel /> (#5380)"

- packages/rest-api-hooks/src/RestApiState.ts
- packages/sak-app/src/behandlingsupport/historikk/HistorikkIndex.tsx
- packages/sak-app/src/fagsak/FagsakIndex.tsx
Reverts navikt/k9-sak-web#5380
> Revert "Unngå doble serverkall pga <LoadingPanel />"

- .github/workflows/promote-command.yml
https://nav-it.slack.com/archives/C01DE3M9YBV/p1702893023861639
> tokenless deploy

- .github/workflows/deploy-docker-image.yml
https://doc.nais.io/guides/oci-migration/
> Bytte ut deprecated ghcr.io registry med GAR

- packages/prosess-omsorgsdager/src/util/stringUtils.ts
https://jira.adeo.no/browse/TSFF-174
> Tillate date for opphør av alene om omsorgen  opp til 18 år frem i tid

- packages/behandling-utvidet-rett/src/panelDefinisjoner/prosessStegPaneler/utvidetRettPanel/utvidetRettMikrofrontend/formateringAvDataTilMikrofrontend/AleneOmOmsorgenObjektTilMikrofrontend.ts
- packages/behandling-utvidet-rett/src/types/utvidetRettMikrofrontend/VilkarAleneOmOmsorgenProps.ts
- packages/prosess-omsorgsdager/src/types/AleneOmOmsorgenProps.ts
- packages/prosess-omsorgsdager/src/ui/components/alene-om-omsorgen/AleneOmOmsorgen.tsx
- packages/prosess-omsorgsdager/src/ui/components/tester/__tests__/alene-om-omsorgen.spec.tsx
- packages/prosess-omsorgsdager/src/util/stringUtils.ts
Dato fra søknaden førte til feil i håndteringen av aksjonspunktet for alene om omsorgen
> Bruk dato fra vilkår istedenfor fra søknad i ap for alene om omsorgen

- packages/prosess-uttak/package.json
- packages/prosess-uttak/src/ui/components/overstyrUttakForm/OverstyrAktivitetListe.tsx
- packages/prosess-uttak/src/ui/components/overstyrUttakForm/OverstyringUttakForm.tsx
- packages/prosess-uttak/src/ui/components/overstyrUttakForm/components/BegrunnelseBoks.tsx
- packages/prosess-uttak/src/ui/components/uttak/Uttak.tsx
- packages/prosess-uttak/src/ui/context/OverstyrUttakContext.tsx
- packages/prosess-uttak/src/util/overstyringUtils.ts
- packages/sak-totrinnskontroll/src/components/AksjonspunktGodkjenningFieldArray.tsx
- yarn.lock
Litt mindre redaksjonelle endringer og små-fiksing. Samt validering på noen av feltene.
> Overstyring uttak validering

- packages/prosess-vedtak/src/components/VedtakSjekkTilbakekreving.spec.tsx
- packages/prosess-vedtak/src/components/VedtakSjekkTilbakekreving.tsx
Reverts navikt/k9-sak-web#5632
> Revert "Redaksjonelle endringer, 5085"

- packages/fakta-overstyr-beregning/package.json
- yarn.lock
> depcheck: Fjerna ubrukte dependencies, la til manglande i fakta-overstyr-beregning

- eslint/eslintrc.common.cjs
Justerer eslint konfigurasjon slik at det blir lov å skrive slik kode:
for(const a of [1,2,3]) {
// do something..
}
> Tillat for - of loop i koden.

- vite.config.js
Bakgrunn: mockServiceWorker.js havner i dist-mappa ved build og blir vel dermed lastet med opp i prod (kjører ikke i prod)
Løsning: Slett den fra dist-mappa i byggsteget
> Funksjon som fjerner mockServiceWorks.js fra dist-mappen

- packages/prosess-vedtak/src/components/VedtakSjekkTilbakekreving.spec.tsx
- packages/prosess-vedtak/src/components/VedtakSjekkTilbakekreving.tsx
Reverts navikt/k9-sak-web#5644
> Prodsetting "Redaksjonelle endringer, 5085""

- packages/sak-app/package.json
- packages/sak-app/src/configureStore.ts
- yarn.lock
Bakgrunn: Meir irriterande enn nyttig å ha den der.
> Fjerner redux-logger.

- packages/fakta-medisinsk-vilkår/src/ui/components/dokument-knapp/DokumentKnapp.tsx
Alternativ til PR #5859 
Trur dette er ein reinare måte å gjere det på.
> Bytter ut linkknapp som åpner dokument

- packages/sak-aktor/i18n/nb_NO.json
- packages/sak-aktor/index.ts
- packages/sak-aktor/package.json
- packages/sak-aktor/src/AktorSakIndex.tsx
- packages/sak-aktor/src/components/AktoerGrid.tsx
- packages/sak-aktor/src/components/aktoerGrid.module.css
- packages/sak-app/package.json
- packages/sak-app/src/aktoer/AktoerIndex.tsx
- packages/sak-app/src/app/components/Home.tsx
- packages/sak-app/src/app/paths.ts
- packages/sak-app/src/data/k9sakApi.ts
- packages/storybook/stories/sak/AktorSakIndex.stories.tsx
- packages/types/index.ts
- packages/types/src/aktorTsType.ts
- yarn.lock
This reverts commit dc6f0122e7996c23b67b424c80e95615df7c5884.
Blir visst sendt hit fra salesforce :S må finne ut hvorfor det er nødvendig
> Revert "fjerner route og komponenter som ikke er i bruk (#5923)"

- .storybook/main.ts
- package.json
- yarn.lock
1. Ser ikkje ut til at getAbsolutePath endringa i .storybook/main.ts er nødvendig når eg tester her.
2. Fjerna testing-react dependency det kom advarsel om. Ser ikkje ut til at den er brukt nokon stad.
> Adjustments to storybook 8 upgrade

- packages/sak-behandling-velger/src/components/BehandlingPickerOld.tsx
Legger inn kommentar for story i PR som rydder i storybook-oppsett
> TSFF-367 - legger inn kommentar for å beskrive komponents hensikt

- packages/sak-totrinnskontroll/src/TotrinnskontrollSakIndex.tsx
- packages/sak-totrinnskontroll/src/components/AksjonspunktGodkjenningFieldArray.tsx
- packages/sak-totrinnskontroll/src/components/TotrinnskontrollBeslutterForm.spec.tsx
- packages/sak-totrinnskontroll/src/components/TotrinnskontrollBeslutterForm.tsx
- packages/sak-totrinnskontroll/src/components/TotrinnskontrollSaksbehandlerPanel.spec.tsx
- packages/sak-totrinnskontroll/src/components/TotrinnskontrollSaksbehandlerPanel.tsx
https://sentry.gc.nav.no/organizations/nav/issues/550746/?project=31&query=is%3Aunresolved&referrer=issue-stream
> debugging sentry

- packages/fakta-opptjening-oms/src/components/activity/ActivityPanel.tsx
Ikke oppfylt istedenfor Avvist
> Redaksjonell endring

- packages/sak-app/src/fagsak/FagsakIndex.tsx
This reverts commit 500ff144cb3edf97e8037018cc80d1cc56e71b9d.
> Revert "vise punsjstripe i tilbakekreving (#6154)"

- packages/behandling-utvidet-rett/src/types/utvidetRettMikrofrontend/VilkarAleneOmOmsorgenProps.ts
- packages/prosess-omsorgsdager/src/types/AleneOmOmsorgenProps.ts
- packages/prosess-omsorgsdager/src/ui/components/alene-om-omsorgen/AleneOmOmsorgen.tsx
- packages/prosess-omsorgsdager/src/ui/components/alene-om-omsorgen/alene-om-omsorgen-tekst.ts
- packages/prosess-omsorgsdager/src/ui/components/tester/__tests__/alene-om-omsorgen.spec.tsx
Inkluder avslagsårsakkode i "Alene om omsorgen" og lag radiogruppe for å velge årsak
> TSFF-511: Avslagsårsak i AO

- packages/fakta-medisinsk-vilkår/package.json
- packages/fakta-medisinsk-vilkår/src/ui/MainComponent.tsx
- packages/fakta-medisinsk-vilkår/src/ui/components/diagnosekodeoversikt/Diagnosekodeoversikt.tsx
- packages/fakta-medisinsk-vilkår/src/ui/components/medisinsk-vilkår/MedisinskVilkår.tsx
- packages/fakta-medisinsk-vilkår/src/ui/components/medisinsk-vilkår/tests/MedisinskVilkår.spec.tsx
- packages/fakta-medisinsk-vilkår/src/ui/context/queryClient.ts
- packages/sak-app/package.json
- packages/sak-app/src/behandlingsupport/BehandlingSupportIndex.tsx
- packages/sak-app/src/fagsak/FagsakIndex.tsx
- packages/sak-behandling-velger/package.json
- packages/sak-behandling-velger/src/BehandlingVelgerSakIndex.tsx
- packages/sak-behandling-velger/src/components/BehandlingPicker.tsx
- packages/sak-dokumenter/package.json
- packages/sak-dokumenter/src/DokumenterSakIndex.tsx
- packages/sak-dokumenter/src/components/DocumentList.spec.tsx
- packages/sak-dokumenter/src/components/DocumentList.tsx
- packages/sak-notat/package.json
- packages/sak-notat/src/NotatISakIndex.stories.tsx
- packages/sak-notat/src/NotaterIndex.tsx
- packages/utils-test/package.json
- packages/utils-test/src/test-utils.tsx
- yarn.lock
Bakgrunn: Vi bruker den utdaterte pakken react-query
Løsning: React-query er nå Tanstack query. Oppgraderer til det
> React query to tanstack

- packages/shared-components/src/tidslinje/TimelinePeriod.tsx
Bruker komponent fra Aksel for tooltip
> Bytter ut komponent for visning av tooltip i tidslinje

- feature-toggles.json
- packages/behandling-utvidet-rett/src/panelDefinisjoner/prosessStegPaneler/utvidetRettPanel/utvidetRettMikrofrontend/formateringAvDataTilMikrofrontend/AleneOmOmsorgenObjektTilMikrofrontend.ts
Legger til default-verdi ettersom noe må sendes om den er togglet av
> Legg til toggle i feature-toggles.json og bruk default-verdi

- packages/sak-behandling-velger/src/components/BehandlingPicker.tsx
Bugen er at den alltid velger den åpne behandlingen, selv om man refresher i en annen behandling
> Reverserer endring som førte til bug

- packages/sak-behandling-velger/src/components/BehandlingPicker.tsx
Reverts navikt/k9-sak-web#6291
> Revert "Legger tilbake navigate i useEffect"

- packages/behandling-frisinn/package.json
- packages/behandling-omsorgspenger/package.json
- packages/behandling-opplaeringspenger/package.json
- packages/behandling-pleiepenger-sluttfase/package.json
- packages/behandling-pleiepenger/package.json
- packages/sak-app/package.json
- yarn.lock
Forsøk på fiks av bug i prosess-beregningsgrunnlag
> Bumper ft-pakke

- vite.config.js
> Fjerner gammal proxy referanse til diagnosekoder service.

- packages/fakta-medisinsk-vilkår/src/types/SykdomsstegStatusResponse.ts
- packages/fakta-medisinsk-vilkår/src/ui/components/medisinsk-vilkår/MedisinskVilkår.tsx
> Viser varselsboks om søker ikke er sammen med barnet under et utenlandsopphold i sykdomssteget.

- deploy/dev-fss-k9saksbehandling.yml
- package.json
- packages/behandling-frisinn/package.json
- packages/behandling-omsorgspenger/package.json
- packages/behandling-opplaeringspenger/package.json
- packages/behandling-pleiepenger-sluttfase/package.json
- packages/behandling-pleiepenger/package.json
- packages/fakta-etablert-tilsyn/package.json
- packages/fakta-inntektsmelding/package.json
- packages/fakta-medisinsk-vilkår/package.json
- packages/fakta-medisinsk-vilkår/src/types/SykdomsstegStatusResponse.ts
- packages/fakta-medisinsk-vilkår/src/ui/components/medisinsk-vilkår/MedisinskVilkår.tsx
- packages/fakta-om-barnet/package.json
- packages/fakta-omsorgen-for/package.json
- packages/prosess-omsorgsdager/package.json
- packages/prosess-uttak/package.json
- packages/prosess-vedtak/package.json
- packages/sak-app/package.json
- packages/sak-app/src/bootstrap.tsx
- packages/v2/backend/package.json
- packages/v2/gui/src/sak/meldinger/FritekstInput.stories.tsx
- packages/v2/gui/src/sak/meldinger/FritekstInput.tsx
- packages/v2/gui/src/sak/meldinger/Messages.tsx
- vite.config.js
- yarn.lock
Merger inn endringer som har skjedd på master, for å halde denne branch kompatibel og enkel å merge dit i framtida.
> Oppdateringer frå master

- packages/v2/backend/README.md
> Fiks v2/backend/README.md

- .github/dependabot.yml
- package.json
- yarn.lock
Småjustering etter dependabot justering.
> Dep adjust

- packages/fakta-feilutbetaling/src/components/FeilutbetalingInfoPanel.jsx
- packages/prosess-avregning/src/components/AvregningPanel.jsx
- packages/prosess-tilbakekreving/src/components/TilbakekrevingPeriodeForm.tsx
Oppdaget at dette også er avhengig av utvidelse i en database i fptilbake. Ettersom dette er en oracle-database er det litt krevende, så reverterer denne frem til dette er fikset
> Reverter til 1500 tegn

- packages/sak-app/src/app/components/Home.tsx
- packages/sak-app/src/fagsak/FagsakIndex.tsx
Endringer i behandlingid trigget ikke i FagsakIndex
> Kodeverk: Flytte context provider for behandling opp

- _mocks/featureToggles.ts
- deploy/dev-fss-k9saksbehandling.yml
- deploy/prod-fss-k9saksbehandling.yml
- feature-toggles.json
- packages/prosess-tilkjent-ytelse/i18n/nb_NO.json
- packages/prosess-tilkjent-ytelse/src/components/manuellePerioder/NyAndel.tsx
Ettersom `erPrivatPerson` ikke returneres må vi bruke `personIdentifikator` for å bestemme om en arbeidsgiver er privatperson eller ikke
> TSFF-775: Fiks filter og legg til ff

- yarn.lock
https://github.com/navikt/k9-sak-web/pull/6566
> Fix sårbarhet i Storybook dependency

- packages/shared-components/src/AksjonspunktHelpText.tsx
Hardkoder tekst som mangler enkelte steder. React-intl skal fases ut.
> Legger inn manglende hjelpetekst

- packages/sak-historikk/src/components/maler/felles/historikkUtils.tsx
Dette er koder som er hardkodet i frontend
> Kodeverk: Slå opp HISTORIKK_ENDRET_FELT_VERDI_TYPE hardkodet

- deploy/dev-fss-k9saksbehandling.yml
Reverts navikt/k9-sak-web#6611
> Revert "Toggler av endringer i prosess-soknadsfrist i Q"

- packages/prosess-vilkar-overstyring/src/VilkarresultatMedOverstyringProsessIndex.tsx
Bakgrunn: Hook ligger på feil sted som gjør at det krasjer
> K9-SAK-WEB-6QV - flytter hook til riktig sted

- packages/fakta-overstyr-beregning/src/components/OverstyrBeregningFaktaForm.tsx
> Sjekker om liste er definert før map-funksjon kjører

- packages/sak-app/src/behandlingmenu/BehandlingMenuIndex.tsx
- packages/sak-app/src/data/k9sakApi.ts
- packages/sak-meny-ny-behandling/i18n/nb_NO.json
- packages/sak-meny-ny-behandling/src/MenyNyBehandlingIndex.spec.tsx
- packages/sak-meny-ny-behandling/src/MenyNyBehandlingIndex.tsx
- packages/sak-meny-ny-behandling/src/components/NyBehandlingModal.spec.tsx
- packages/sak-meny-ny-behandling/src/components/NyBehandlingModal.tsx
- packages/sak-meny-ny-behandling/src/components/nyBehandlingModal.module.css
This reverts commit 772199e55f9d76eee2ba322c9d3004add94ac3a5.
> Midlertidig revert for prodsetting "Implementer ny revurderingsflyt med gammel tech (#6659)"

- packages/prosess-tilkjent-ytelse/src/components/manuellePerioder/TilkjentYtelseForm.tsx
Skaper problemer med validering i backend
> Fjern beskrivelse: '' fra TilkjentYtelseForm

- packages/sak-meny-ny-behandling/src/components/NyBehandlingModal.tsx
Delvise revurderinger burde alltid ha fylt ut en fra og til dato.
> Legg til validering på at fra og til dato er satt

- eslint.config.mjs
- packages/fakta-medisinsk-vilkår/src/ui/components/diagnosekodeoversikt/Diagnosekodeoversikt.tsx
- packages/shared-components/src/andreSakerPaSokerStripe/AndreSakerPåSøkerStripe.tsx
- packages/v2/backend/package.json
- yarn.lock
Kan hjelpe med å fange opp gotchas i bruk av tanstack query.
> Legger til linting for tanstack query kode.

- packages/v2/gui/src/prosess/uttak/vurder-overlappende-sak/VurderOverlappendeSak.tsx
- packages/v2/gui/src/utils/aksjonspunkt.ts
Rediger knappen var aktiv når saken var hos beslutter
> Skal ikke kunne redigere aksjonspunkt når sak hos beslutter

- package.json
For å forhindre at dependabot setter en høyere versjon igjen
> Tvinger storybook til å holde seg på 8.4.7

- eslint.config.mjs
- package.json
- yarn.lock
Plugin støtter ikke flat config ennå så må gjøres på gamlemåten. Kan endres når denne er løst https://redirect.github.com/facebook/react/pull/30774#issuecomment-2622784958
> Legger inn warnings for feil bruk av hooks

- packages/sak-historikk/i18n/nb_NO.json
- packages/sak-historikk/src/components/History.tsx
- packages/sak-historikk/src/kodeverk/historikkEndretFeltTypeCodes.ts
- packages/sak-historikk/src/kodeverk/historikkEndretFeltTypeHeadingCodes.ts
> TSFF-1142: Historikk for fastsetting av uttaksgrad i ved søskensakaksjonspunkt

- packages/behandling-pleiepenger/src/components/MedisinskVilkår.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/faktaPaneler/MedisinskVilkarFaktaPanelDef2.tsx
- packages/fakta-medisinsk-vilkår/src/types/ContainerContract.ts
- packages/fakta-medisinsk-vilkår/src/ui/components/innleggelsesperiodeFormModal/InnleggelsesperiodeFormModal.tsx
- packages/fakta-medisinsk-vilkår/src/ui/components/innleggelsesperiodeoversikt/Innleggelsesperiodeoversikt.tsx
https://jira.adeo.no/browse/TSFF-1130
> TSFF-1130 - validering på om dato er før fødselsdato

- loosely-type-checked-files.json
- packages/form/src/DatepickerField.tsx
- packages/prosess-vedtak/src/components/AvslagsårsakListe.spec.tsx
- packages/prosess-vedtak/src/components/VedtakAvslagPanel.spec.tsx
- packages/sak-meny-ny-behandling/src/MenyNyBehandlingIndex.spec.tsx
- packages/sak-meny-ny-behandling/src/MenyNyBehandlingIndex.tsx
- packages/sak-meny-ny-behandling/src/VilkårBackendClient.ts
- packages/sak-meny-ny-behandling/src/components/NyBehandlingModal.tsx
- packages/shared-components/src/datepicker/Datepicker.tsx
- packages/v2/backend/package.json
- packages/v2/backend/src/k9sak/kodeverk/behandling/VilkårStatus.ts
- packages/v2/backend/src/k9sak/kodeverk/behandling/VilkårType.ts
- yarn.lock
> TSFF-1129 - gjør det mulig å revurdere datoer frem i tid

- packages/behandling-frisinn/package.json
- packages/behandling-omsorgspenger/package.json
- packages/behandling-opplaeringspenger/package.json
- packages/behandling-pleiepenger-sluttfase/package.json
- packages/behandling-pleiepenger/package.json
- packages/sak-app/package.json
- yarn.lock
Har en sak der aksjonspunkt 5039 kommer i en sak etter 5038 er løst. Submitknapp har fortsatt spinner og man får ikke løst 5039.
Låse opp submitknapp dersom man får nye avklaringsbehov. https://github.com/navikt/ft-frontend-saksbehandling/pull/3595
> FAGSYSTEM-374401 - Bump ft-pakke

- packages/v2/gui/src/prosess/uttak/vurder-overlappende-sak/VurderOverlappendeSak.stories.tsx
@thomashwi skal fikse ved første anledning ❤️
> Kommenterer ut flaky tester midlertidig

- packages/behandling-frisinn/package.json
- packages/behandling-omsorgspenger/package.json
- packages/behandling-opplaeringspenger/package.json
- packages/behandling-pleiepenger-sluttfase/package.json
- packages/behandling-pleiepenger/package.json
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/BeregningsgrunnlagProsessStegPanelDef.tsx
- packages/sak-app/package.json
- yarn.lock
https://github.com/navikt/ft-frontend-saksbehandling/pull/3596
> Funksjon for å sende melding til Sentry om feil

- packages/behandling-frisinn/package.json
- packages/behandling-omsorgspenger/package.json
- packages/behandling-opplaeringspenger/package.json
- packages/behandling-pleiepenger-sluttfase/package.json
- packages/behandling-pleiepenger/package.json
- packages/sak-app/package.json
- yarn.lock
https://github.com/navikt/ft-frontend-saksbehandling/pull/3597
> Bumper ft-prosess-beregning for å rette prodfeil

- packages/v2/gui/src/prosess/ung-beregning/ArbeidOgInntekt.tsx
> Kommenterer ut felter for å fikse typescript-publsering.

- packages/v2/gui/src/prosess/uttak/vurder-overlappende-sak/VurderOverlappendeSak.stories.tsx
- Feil relativ dato brukt et par steder
- Test feiler også på at det virker som user.type ikke trigger de riktige funksjonene så verdien er visuelt synlig i storybook, men blir ikke med programatisk. fireEvent.change fungerer som forventet.
> Bug overlappende

- packages/v2/gui/src/prosess/ung-beregning/ArbeidOgInntekt.tsx
> ung: Sjekker om fastsattinntekt er ulik null og undefined

- packages/v2/gui/src/prosess/avregning/kontroller-etterbetaling/KontrollerEtterbetaling.stories.tsx
- packages/v2/gui/src/prosess/uttak/vurder-overlappende-sak/VurderOverlappendeSak.stories.tsx
Byttet ikke måned før valg av dato om splitt gikk på tvers av måneder.
> Overlappende ytelser test bug

- packages/v2/backend/package.json
- packages/v2/gui/src/prosess/ung-vedtak/UngVedtak.tsx
- packages/v2/gui/src/prosess/ung-vedtak/UngVedtakBackendApiType.ts
- packages/v2/gui/src/prosess/ung-vedtak/UngVedtakBackendClient.ts
- packages/v2/gui/src/storybook/mocks/FakeUngVedtakBackendApi.ts
- ung.vite.config.js
- yarn.lock
Endrer til å støtte nye genererte typer
> Ung: fritekstbrev del 1

- packages/v2/backend/package.json
- packages/v2/gui/src/prosess/ung-beregning/ArbeidOgInntekt.tsx
- packages/v2/gui/src/prosess/ung-beregning/UngBeregning.tsx
- yarn.lock
Lagrer en sammenstilling av alle begrunnelser i aksjonspunktet.
> ung: Bruker begrunnelse fra hver periode i AP 8000

- packages/v2/gui/src/prosess/ung-beregning/DataSection.tsx
> Ung: Viser ikke sluttdato før den finnes

- packages/ung/sak-app/fagsak/FagsakIndex.tsx
- packages/v2/gui/src/sak/visittkort/VisittkortPanel.tsx
Disse detaljene er ikke relevant for ytelsen
ref https://github.com/navikt/ung-sak/pull/332
> Ung: Viser ikke popup i visittkort med detaljer om søker

- packages/behandling-ungdomsytelse/src/components/UngdomsytelseProsess.spec.tsx
- packages/behandling-ungdomsytelse/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/AlderPanelDef.tsx
- packages/behandling-ungdomsytelse/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/SoknadsfristPanelDef.tsx
- packages/behandling-ungdomsytelse/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/UngdomsprogramPanelDef.tsx
- packages/kodeverk/src/vilkarType.ts
- packages/v2/backend/package.json
- packages/v2/gui/src/prosess/ung-vedtak/UngVedtak.stories.tsx
- yarn.lock
Oppdaterer typene for inngangsvilkår etter endringer
> Ung: inngangsvilkartyper

- packages/v2/gui/src/shared/aksjonspunktBox/AksjonspunktBox.tsx
- packages/v2/gui/src/shared/aksjonspunktBox/aksjonspunktBox.module.css
Spesifiserer fortsatt "vår" gulfarge på border
> Oppdater AksjonspunktBox til å bruke Aksel Box komponent

- packages/v2/gui/src/prosess/avregning/kontroller-etterbetaling/KontrollerEtterbetalingAlert.tsx
- packages/v2/gui/src/shared/ContentMaxWidth/ContentMaxWidth.tsx
- packages/v2/gui/src/shared/aksjonspunktBox/aksjonspunktBox.module.css
Bytter navn på komponenten til et noe mer beskrivende navn
> Content max width

- loosely-type-checked-files.json
- packages/prosess-avregning/src/components/AvregningSummary.jsx
- packages/prosess-avregning/src/components/AvregningTable.tsx
- packages/prosess-avregning/src/components/CollapseButton.jsx
- packages/v2/gui/src/prosess/avregning/kontroller-etterbetaling/KontrollerEtterbetaling.tsx
Justerer litt fonter som er for store i panelet for avregning, samt litt types som ikke stemte.
> Avregning fonts and types

- packages/prosess-uttak/src/ui/components/uttak/UttakRad.tsx
- packages/prosess-uttak/src/ui/components/uttak/UttakRadOpplæringspenger.tsx
- packages/prosess-uttak/src/ui/components/uttaksperiode-liste/UttaksperiodeListe.tsx
- packages/prosess-uttak/src/vilkårsliste/Vilkår.ts
Blir en del forskjeller fra pleiepenger i komponenten, og det blir rotete med alle variablene
Skiller ut i rad-komponent i opplæringspenger
> Egen UttakRad for opplæringspenger

- packages/v2/gui/src/app/feilmeldinger/ErrorBoundary.tsx
error state var ikkje satt i ErrorBoundary instans når shouldReportToSentry vart kalla. Dermed vart returverdi alltid true.
Sender error inn til shouldReportToSentry som argument istadenfor, slik at den fungerer som tenkt.
> Fikser ErrorBoundary shouldReportToSentry.

- packages/v2/backend/package.json
- packages/v2/gui/src/prosess/ung-beregning/UngBeregning.tsx
- packages/v2/gui/src/prosess/ung-beregning/UngBeregningBackendApiType.ts
- packages/v2/gui/src/prosess/ung-beregning/UngBeregningBackendClient.ts
- packages/v2/gui/src/prosess/ung-beregning/dagsats-og-utbetaling/BeregningsDetaljer.tsx
- packages/v2/gui/src/prosess/ung-beregning/dagsats-og-utbetaling/BeregningsDetaljerUtregning.tsx
- packages/v2/gui/src/prosess/ung-beregning/dagsats-og-utbetaling/DagsatsOgUtbetaling.tsx
- packages/v2/gui/src/prosess/ung-beregning/dagsats-og-utbetaling/DataCellWithValue.tsx
- packages/v2/gui/src/prosess/ung-beregning/dagsats-og-utbetaling/DataSection.tsx
- packages/v2/gui/src/prosess/ung-beregning/dagsats-og-utbetaling/dagsatsOgUtbetaling.module.css
- packages/v2/gui/src/prosess/ung-beregning/dagsats-og-utbetaling/dagsatsOgUtbetaling.module.d.css.ts
- packages/v2/gui/src/prosess/ung-beregning/dagsats-og-utbetaling/dagsatsUtils.tsx
- packages/v2/gui/src/storybook/mocks/FakeUngBeregningBackendApi.ts
- packages/v2/gui/src/utils/formatters.spec.ts
- packages/v2/gui/src/utils/formatters.ts
- yarn.lock
Viser utbetalingsperioder gruppert på måned. Dersom en måned har flere satsperioder vises disse under måneden.
Viser regnestykket for siste utbetaling.
> Ung månedsvis sats

- packages/v2/gui/src/prosess/uttak/uttak-detaljer/GraderingMotArbeidstidDetaljer.tsx
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/GraderingMotInntektDetaljer.tsx
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/UttakDetaljer.tsx
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/UttakDetaljerEkspanderbar.tsx
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/uttakDetaljer.module.css
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/uttakUtregning.module.css
Virker ikke som syntaxen på css klassene spiller på lag med typeGen etc.
> Juster CSS

- packages/v2/gui/src/sak/totrinnskontroll/TotrinnskontrollSakIndex.tsx
Beslutterpanelet vises ikke i `REVURDERING_TILBAKEKREVING` saker
> REVURDERING_TILBAKEKREVING er også en tilbakekreving

- packages/v2/gui/src/shared/vurderingsperiode-navigasjon/VurderingsperiodeNavigasjon.tsx
Får ikke opprettet ny periode i uperiodisert sykdom pga useEffect i periodenavigassjon
Setter vurdering i visning automatisk kun èn gang
> Får ikke opprettet ny periode i uperiodisert sykdom

- packages/behandling-opplaeringspenger/src/panelDefinisjoner/faktaOpplaeringspengerPanelDefinisjoner.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/faktaPaneler/VergeFaktaPanelDef.tsx
- packages/behandling-pleiepenger-sluttfase/src/panelDefinisjoner/faktaPaneler/VergeFaktaPanelDef.tsx
- packages/behandling-pleiepenger-sluttfase/src/panelDefinisjoner/faktaPleiepengerSluttfasePanelDefinisjoner.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/faktaPaneler/VergeFaktaPanelDef.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/faktaPleiepengerPanelDefinisjoner.tsx
Har en sak i prod hvor en mindreårig har søkt om pleiepenger og vi får aksjonspunkt om vergemål. Vi har ikke muligheten til å løse aksjonspunktet via brukergrensesnittet
Kopierer inn vergemålspanelet fra omsorgspenger
> Legger til panel for å løse vergemål

- packages/fakta-medisinsk-vilkår/src/api/api.ts
Flagg for mangler legeerklæring manger ved endring av vurdering i medisinsk vilkår
Ta med flagg for manglerLegeerklæring
> Ta med manglerLegeerklæring ved endring av vurdering

- packages/v2/gui/src/fakta/sykdom-og-opplæring/SykdomOgOpplæringBackendClient.ts
- packages/v2/gui/src/fakta/sykdom-og-opplæring/SykdomOgOpplæringQueries.ts
Oppdatering skjer nå gjennom aksjonspunkt, ikke eget endepunkt.
Fjern wrapper
> Fjern wrapper for utdatert endepunkt

- packages/v2/gui/src/shared/vurderingsperiode-navigasjon/PeriodeRad.tsx
- packages/v2/gui/src/shared/vurderingsperiode-navigasjon/periodeRad.module.css
Klassene for bakgrunnsfarge i tailwind kan visste ikke brukes mer(?) pga Aksel Darkside. Klassene gir ingen styling.
Setter fargen med god gammel css
> fix - setter bakgrunnsfarge med css i steder for tailwind

- packages/fakta-medisinsk-vilkår/src/ui/components/dokumentoversikt-messages/DokmentoversiktMessages.tsx
> Fix - bruker variant info for alle ytelser

- packages/v2/gui/src/fakta/medlemskap/components/oppholdInntektOgPerioder/PerioderMedMedlemskapFaktaPanel.tsx
- packages/v2/gui/src/fakta/medlemskap/types/FormState.ts
- packages/v2/gui/src/fakta/medlemskap/types/Periode.ts
Backend likte ikke at jeg sendte inn tom streng.
Bytter til undefined.
> Fix: backend liker ikke tomme strenger, bytter til undefined

- packages/behandling-felles/src/components/InngangsvilkarPanel.tsx
- packages/fakta-medisinsk-vilkår/src/ui/components/nye-dokumenter-som-kan-påvirke-eksisterende-vurderinger/NyeDokumenterSomKanPåvirkeEksisterendeVurderinger.tsx
- packages/prosess-klagevurdering/src/components/felles/TempSaveAndPreviewKlageLink.tsx
- packages/prosess-vedtak-tilbakekreving/src/components/TilbakekrevingVedtakForm.tsx
- packages/prosess-vedtak-tilbakekreving/src/components/tilbakekrevingVedtakForm.module.css
- packages/sak-meldinger/src/components/Messages.tsx
- packages/sak-meldinger/src/components/MessagesTilbakekreving.tsx
- packages/v2/gui/src/app/alerts/ErrorAlert.tsx
- packages/v2/gui/src/app/feilmeldinger/BigError.tsx
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/UttakDetaljerEkspanderbar.tsx
- packages/v2/gui/src/prosess/uttak/vurder-overlappende-sak/VurderOverlappendeSak.tsx
- packages/v2/gui/src/sak/behandling-velger/components/BehandlingSelected.tsx
- packages/v2/gui/src/sak/dokumenter/DokumenterSakIndex.stories.tsx
- packages/v2/gui/src/sak/dokumenter/components/DocumentList.tsx
- packages/v2/gui/src/sak/dokumenter/components/documentList.module.css
- packages/v2/gui/src/sak/historikk/innslag/InnslagLinje.tsx
- packages/v2/gui/src/sak/historikk/snakkeboble/HistorikkDokumentLenke.tsx
- packages/v2/gui/src/sak/historikk/snakkeboble/Skjermlenke.tsx
- packages/v2/gui/src/sak/totrinnskontroll/components/AksjonspunktGodkjenningFieldArray.tsx
- packages/v2/gui/src/sak/totrinnskontroll/components/TotrinnskontrollSaksbehandlerPanel.tsx
Vi har lenker i ulike varianter og farger. Ønsker å standardisere.
Bruker Link fra Aksel alle steder
> Bruker Link fra Aksel for alle lenker

- loosely-type-checked-files.json
- packages/fakta-barn-oms/src/components/BarnVisning.spec.tsx
> Gratulerer med dagen til testperson BarnVisning.spec.tsx

- packages/behandling-tilbakekreving-ungdomsytelse/package.json
- packages/behandling-tilbakekreving-ungdomsytelse/src/components/ForeldelseProsessIndexWrapper.tsx
- packages/behandling-tilbakekreving-ungdomsytelse/src/kodeverk/relasjonsRolleTypeKodeverk.ts
- packages/behandling-tilbakekreving/package.json
- packages/behandling-tilbakekreving/src/components/ForeldelseProsessIndexWrapper.tsx
- packages/behandling-tilbakekreving/src/kodeverk/relasjonsRolleTypeKodeverk.ts
- yarn.lock
https://jira.adeo.no/browse/TSFF-1916
Sender ned deltaker som rolletype for ung-sak-web
Gjort samme endring av importer i behandling-tilbakekreving for k9-sak-web
> TSFF-1916 - endrer visningsnavn til deltaker for ung

- packages/ung/sak-app/behandlingmenu/BehandlingMenuIndex.tsx
- packages/ung/sak-app/fagsakprofile/FagsakProfileIndex.tsx
- packages/v2/gui/src/sak/meny/ta-av-vent/MenyTaAvVentIndex.spec.tsx
- packages/v2/gui/src/sak/meny/ta-av-vent/MenyTaAvVentIndex.stories.tsx
- packages/v2/gui/src/sak/meny/ta-av-vent/MenyTaAvVentIndex.tsx
- packages/v2/lib/src/paths/paths.ts
Kan ikke ta behandling av vent i ung
Løser det ved å sende riktig parameter.
Endrer logikk for når behandlingmeny skal være disabled. Endrer til kun disabled for prod.
> TSFF-1915 - fikser ta behandling av vent for ung

- packages/prosess-vedtak/package.json
- yarn.lock
Reverts navikt/k9-sak-web#7819
> Revert "Prøve å rulle tilbake editorjs"

- packages/prosess-tilbakekreving/src/components/TilbakekrevingForm.tsx
Flaky test for prosess-tilbakekreving som feiler støtt og stadig
> Prøver å fikse flaky tilbakekrevingstest

- packages/fakta-medisinsk-vilkår/package.json
- packages/sak-app/package.json
- packages/sak-app/src/fagsakprofile/FagsakProfileIndex.tsx
- packages/ung/sak-app/package.json
- packages/utils-test/package.json
- packages/v2/gui/package.json
- yarn.lock
Feil i react-query fører til evig rerenders
https://github.com/TanStack/query/issues/9638
Bumper react-query
Bruker memoisering av props til komponent som kan føre til unødvendige rerenders
> Fikser rerender-feil som fører til store performance problemer

- packages/sak-app/src/fagsak/FagsakIndex.tsx
- packages/v2/backend/package.json
- packages/v2/gui/src/shared/statusstriper/K9StatusBackendApi.ts
- packages/v2/gui/src/shared/statusstriper/K9StatusBackendClient.ts
- packages/v2/gui/src/shared/statusstriper/andreSakerPaSokerStripe/AndreSakerPåSøker.stories.tsx
- packages/v2/gui/src/shared/statusstriper/andreSakerPaSokerStripe/AndreSakerPåSøkerStripe.tsx
- yarn.lock
Opning av behandlinger for klage/tilbakekreving førte til feil ved kall til server for å finne relaterte fagsaker.
Bruker saksnummer som input til server søk istadenfor behandling. Skal då fungere for alle behandlinger.
> Relaterte saker fagsak

- packages/sak-app/src/behandlingmenu/BehandlingMenuIndex.tsx
- packages/sak-app/src/fagsak/sakRettigheterTsType.ts
- packages/ung/sak-app/behandlingmenu/BehandlingMenuIndex.tsx
- packages/v2/gui/src/sak/meny/ny-behandling/MenyNyBehandlingIndex.stories.tsx
- packages/v2/gui/src/sak/meny/ny-behandling/components/NyBehandlingModal.spec.tsx
- packages/v2/gui/src/sak/meny/ny-behandling/components/NyBehandlingModal.tsx
https://jira.adeo.no/browse/TSFF-2047
> TSFF-2047 - Manuell revurdering av inntektskontroll for ungdomsprogramytelsen

- packages/sak-app/src/behandlingmenu/BehandlingMenuIndex.tsx
- packages/ung/sak-app/behandlingmenu/BehandlingMenuIndex.tsx
- packages/v2/gui/src/sak/meny/sett-paa-vent/MenySettPaVentIndex.spec.tsx
- packages/v2/gui/src/sak/meny/sett-paa-vent/MenySettPaVentIndex.stories.tsx
- packages/v2/gui/src/sak/meny/sett-paa-vent/MenySettPaVentIndex.tsx
TSFF-2082
Ung og K9 skal oppføre seg ulikt etter at sak er satt på vent
Send en funksjon som håndterer dette som prop
> TSFF-2082 - send navigering etter submit som prop

- packages/v2/gui/src/fakta/sykdom-og-opplæring/TabIcons.tsx
- packages/v2/gui/src/shared/DelvisOppfyltIkon.tsx
- packages/v2/gui/src/shared/labelled-content/LabelledContent.tsx
Forvirrende for saksbehandlerne
> Fjerne ikon for delvis oppfylt i sykdom og opplæring

- deploy/ung/dev-gcp.yml
- deploy/ung/prod-gcp.yml
- start-server.sh
- ung.proxy.nginx
Reverts navikt/k9-sak-web#7942
> Revert "Mildertidig fjerning av ung-tilbake i Q for å muliggjøre deploy"

- packages/v2/gui/src/fakta/medlemskap/components/oppholdInntektOgPerioder/MedlemskapEndringerTabell.tsx
- packages/v2/gui/src/prosess/vilkar-soknadsfrist/components/SoknadsfristVilkarForm.tsx
> Fiks for farge som har falt ut i aksjonspunktikon
