- packages/sak-app/src/app/AppConfigResolver.jsx
- packages/sak-app/src/behandlingmenu/BehandlingMenuIndex.jsx
Move rest-call on behandlende-enheter from AppConfigResolver to BehandlingMenuIndex
to make ytelseType available when the rest call is made
> behandlende-enheter ytelseType-param

- packages/prosess-vedtak-klage/src/components/VedtakKlageForm.jsx
- packages/prosess-vedtak-klage/src/components/VedtakKlageForm.spec.jsx
`behandlingsresultat` finnes ikke på klage sin `BehandlingDto`. Resultatet må derfor hentes fra `klageVurdering`.
Koden her var forøvrig ganske rotete og forvirrende, blant annet med tre forskjellige ting som het `klageVurdering` og en selector som endret innholdet i sin egen kilde. Jeg har prøvd å rydde litt i dette, bl.a. ved å legge til en ny prop som heter `klageresultat`.
> Rydder kode og henter klageresultat fra riktig sted

- packages/sak-app/src/behandlingsupport/approval/ApprovalIndex.jsx
Per nå får ikke `ApprovalIndex` all informasjonen den trenger om en klagebehandling. Dette er fordi endepunktet `fpsakApi.TOTRINNS_KLAGE_VURDERING` ikke er oppdatert med sti fra klagebehandling når komponenten lastes inn. Jeg har løst dette ved å hente inn endepunktstiene som tilhører behandlingen og oppdatere `reduxRestApi` med disse i `render()`. Ser at liknende metoder er brukt andre steder, f.eks. på [BehandlingIndex](https://github.com/navikt/k9-sak-web/blob/master/packages/sak-app/src/behandling/BehandlingIndex.jsx) og [BehandlingKlageIndex](https://github.com/navikt/k9-sak-web/blob/master/packages/behandling-klage/src/BehandlingKlageIndex.tsx).
> Legger til klageinformasjon på ApprovalIndex

- packages/prosess-formkrav/src/components/FormkravKlageForm.jsx
- packages/prosess-formkrav/src/components/FormkravKlageFormKa.jsx
- packages/prosess-formkrav/src/components/FormkravKlageFormNfp.jsx
Behandlings-ID finnes ikke i `klageFormkravResulat` - denne må derfor hentes fra lista over avsluttede behandlinger. Refaktorerer også `IKKE_PA_KLAGD_VEDTAK` -> `IKKE_PAKLAGD_VEDTAK`.
> Henter inn behandlingsid til nedtrekksmeny for påklagd vedtak

- packages/behandling-omsorgspenger/src/panelDefinisjoner/prosessStegOmsorgspengerPanelDefinisjoner.tsx
Legger på manglende håndtering av statusen til TilkjentYtelseProsessIndex i prosessmenyen for
tilfellet hvor beregningsresultatUtbetaling.perioder er en tom liste. Resulterte tidligere i
undefined-feil.
> Tilkjent Ytelse fix

- packages/sak-app/src/behandlingsupport/approval/ApprovalIndex.jsx
Denne koden ble tidligere lagt til fordi `ApprovalIndex` ikke fikk all informasjonen den trengte om en klagebehandling. Nå hentes den imidlertid inn på konvensjonelt vis via fagsakkontekst og `ApprovalIndex` får dermed informasjonen derfra.
> Fjerner kode som ikke bør være der

- packages/prosess-vedtak/src/components/revurdering/VedtakRevurderingForm.jsx
Har oversett at `simuleringResultat` har en annen `simuleringResultat` inni seg.
> Fiks: Finner feilutbetaling på rett sted

- packages/prosess-aarskvantum-oms/src/components/AktivitetTabell.tsx
- packages/shared-components/src/table/TableRow.tsx
`tabIndex={-1}` løste ikke problemet med uønsket fokus. Radene får fortsatt fokus ved museklikk. `null` gjør at `tabindex` blir fjernet fra HTML-elementet. Jeg har også lagt til `notFocusableHeader` på uttakstabellen - denne ble ved en feil utelatt fra min forrige pull request.
> Gjør at radene i uttakstabellen ikke er fokuserbare

- packages/shared-components/src/table/Table.tsx
Innføring av `withoutTbody` på `Table` gjorde at `noHover` ble satt på `tbody` i stedet for på radene når man grupperte rader i flere tbodies. Jeg har derfor utvidet komponenten slik at `noHover` blir arvet av alle rader uansett om `withoutTbody` er satt eller ikke.
> Fikser noHover-error

- packages/behandling-frisinn/src/panelDefinisjoner/prosessStegPaneler/BeregningsgrunnlagProsessStegPanelDef.tsx
- packages/behandling-frisinn/src/panelDefinisjoner/prosessStegPaneler/SimuleringProsessStegPanelDef.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/BeregningsgrunnlagProsessStegPanelDef.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/SimuleringProsessStegPanelDef.tsx
- packages/behandling-unntak/src/panelDefinisjoner/prosessStegPaneler/SimuleringProsessStegPanelDef.tsx
- packages/behandling-unntak/src/panelDefinisjoner/prosessStegPaneler/UnntakProsessStegPanelDef.tsx
Ref commit: https://github.com/navikt/k9-sak-web/blob/a5c17e96b96e457ba28523fddcba86e532996610/packages/behandling-felles/src/components/ProsessStegPanel.tsx där vi la till featureToggle i data objektet.
> Fjernat featureToggle i processPanel definitionen

- packages/utils/src/validation/validatorsHelper.ts
Legger til bindestrek (hyphen) og bindestrek (Non-breaking hyphen) som ikke bryter teksten. Valideringen godtar fra før bindestrek (dash) og plain `-`.
Word/Pdf oversetter plain `-` til bindestreker, som gjør at kopiering fra mal er mye styr.
Her er resten av unicode-jungelen av bindestreker: https://www.compart.com/en/unicode/category/Pd
> Legger til bindestrek (hyphen) og bindestrek (Non-breaking hyphen)

- .github/workflows/promote-command.yml
Ikke støtte før short sha ref i v2 per https://github.com/actions/checkout/issues/265
> Nedgradere checkout action till v1 i promote

- packages/konstanter/src/eksterneLenker.ts
må gå til forsiden, kan ikke søke opp person på https://arbeid-og-inntekt.nais.adeo.no/inntekt/
> fjerner /inntekt/ fra A-inntekt lenke

- packages/prosess-vedtak/src/components/VedtakForm.jsx
- packages/prosess-vedtak/src/components/VedtakForm.spec.jsx
- packages/prosess-vedtak/src/components/revurdering/VedtakRevurderingForm.jsx
Formidling trenger egen fritekst i endringsbrev, og vil legge ved koden `REVURDERING_ENDRING` med beskrivelse, når det er nødvendig.
> Lagt til nytt fritekstbehov for formidling

- packages/fakta-barn-oms/src/FaktaBarnIndex.tsx
Hade tidigare kun fødelsdato når det kom till rammevedtak men må nå støtte att flere kombinasjoner av fnr og fødselsdato
> Tillrettelegger for flere muligheter av fnr og fødselsdato

- .storybook/main.js
- packages/prosess-vedtak/src/components/FritekstBrevPanel.tsx
- packages/prosess-vedtak/src/components/VedtakAksjonspunktPanel.tsx
- packages/prosess-vedtak/src/components/VedtakForm.tsx
- packages/prosess-vedtak/src/components/VedtakOverlappendeYtelsePanel.tsx
- packages/prosess-vedtak/src/components/brev/MellomLagreBrev.tsx
- packages/storybook/stories/prosess/VedtakProsessIndex.stories.js
Tekst og designendringer
Fjernet eslint fra storybook-bygg som gjorde oppstart latterlig tregt
> Viser alltid aksjonspunktvisning for overlappende ytelser

- packages/sak-meldinger/src/components/Messages.tsx
- packages/types/src/meldingTsType.ts
Jira: TSF-2465
Formidling sender ved et felt harVarsel: true/false på mottakere til malene i brevmenyen. Nå settes det kun true hvis organisasjonen har opphørt.
> Filtrere bort avsluttede arbeidsgivere i brevmenyen (papirflymenyen)

- packages/prosess-vedtak/package.json
- yarn.lock
This reverts commit 2b9788b1d6705fa63efc641c69cf579098d38677.
> Revert "Bump @editorjs/editorjs from 2.27.2 to 2.28.0 (#4937)"

- packages/sak-meldinger/src/components/Messages.tsx
Fekk undefined feil ved opning av komponent i storybook (sak-meldinger).
~~Antar det potensielt også kan skje i reell drift ut frå slik koden er skrive.~~  commit log melding tyder på at dette kanskje berre er ei problemstilling i utvikling/test
> Unngå feil når valgtBrevmal er undefined i Messages.tsx

- packages/rest-api-hooks/src/RestApiState.ts
- packages/sak-app/src/behandlingsupport/historikk/HistorikkIndex.tsx
- packages/sak-app/src/fagsak/FagsakIndex.tsx
Fikser nokon stader der sidekomponenter som laster data frå server vart rendra eit lite øyeblikk, før dei vart erstatta med visning av LoadingPanel pga datalasting frå server lenger ute i komponenthierarkiet. Slik rendering medføre at serverkall for datalasting frå komponenter lenger nede i hierarkiet skjer fleire ganger uten nokon god grunn.
Det er sannsynlegvis fleire stader i koden der dette er eit problem. Sjå etter kode som sjekker på xxx === RestApiState.LOADING uten å sjekke xxx === RestApiState.NOT_STARTED.
> Unngå doble serverkall pga <LoadingPanel />

- packages/prosess-vedtak-tilbakekreving/src/components/TilbakekrevingVedtakForm.spec.tsx
- packages/prosess-vedtak-tilbakekreving/src/components/brev/TilbakekrevingEditerVedtaksbrevPanel.spec.tsx
- packages/prosess-vedtak-tilbakekreving/src/components/brev/TilbakekrevingEditerVedtaksbrevPanel.tsx
- packages/prosess-vedtak-tilbakekreving/src/components/brev/tilbakekrevingEditerVedtaksbrevPanel.module.css
Bakgrunn: Gammel komponent lukker seg når inputfelter har fått tekst og åpen-prop endres (som egentlig bare skal styre default åpen) til false.
Løsning: Bytt til ny komponent fra ds-react som ser lik ut men som er forbedret
> Bytter ut gammel komponent med problemer til ny

- packages/sak-historikk/src/components/maler/felles/bubbleText.module.css
- packages/sak-historikk/src/components/maler/felles/bubbleText.spec.tsx
- packages/sak-historikk/src/components/maler/felles/bubbleText.tsx
Bakgrunn: Lenke scrollet hele vinduet til toppen ved klikk.
Løsning: Knapp er mer egnet her, og scroller ikke vinduet til toppen
> Bytter fra anchor til knapp i historikkinnslag

- package.json
Bakgrunn: Pre commit-hookene formaterte ikke typescript-filer.
Løsning: Legg inn at typescript-filer også skal formateres. Snevrer det også inn til at bare koden i packages-mappen skal formateres
> forbedrer  pre-commit hookene

- packages/sak-dekorator/src/HeaderWithErrorPanel.spec.tsx
- packages/sak-dekorator/src/HeaderWithErrorPanel.tsx
Bakgrunn: Endringsloggen rendres i popupen som dukker opp for innlogging, og fører alltid til feilende kall mot endringslogg backend som støyer i Sentry-loggene.
Løsning: Ikke rendre endringslogg dersom url er den som brukes i popup
> Endre logikk for om endringslogg skal rendres

- packages/behandling-pleiepenger/package.json
- packages/fakta-medisinsk-vilkår/package.json
- yarn.lock
**Bakgrunn:**
Nye diagnosekoder er gjeldande frå 1. januar 2024
**Løsning**
Oppdater til versjon 1.2024.0 av @navikt/diagnosekoder
> Bruk diagnosekoder for 2024.

- packages/sak-meldinger/src/components/Messages.tsx
Ved forhåndsvisning får pr no ikkje trigga validering i frontend. Så for at bruker skal få fornuftig feilmelding må vi sende ugyldig (tredjeparts)mottaker-orgnr til backend når det er snakk om kall for forhåndsvisning.
> Forhåndsvisning brev: Send ugyldig orgnr til backend.

- deploy/prod-fss-k9saksbehandling.yml
Bakgrunn: Bruker per nå pakker fra k9-saksbehandling-frontend-repoet.
Løsning: Disse pakkene er kopiert inn i dette repoet. Bytter over til å bruke de lokale
> Slår på bruk av lokale pakker i prod

- packages/prosess-uttak/src/ui/components/overstyrUttakForm/OverstyrUttakForm.tsx
- Fikk med en unødvendig ID som ble skrevet ut i modalen
- If sjekken gjorde at man ikke fikk bekreftet aksjonspunktet hvis man ønsket å fjerne overstyringene og gå videre
> Overstyr uttak fix 2

- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/UttakProsessStegPanelDef.tsx
En liten d ble til en stor D i overføringen fra microfrontend, og som de fleste vet (foruten meg) så er ikke `virkningsdatoUttakNyeRegler` det samme som `virkningsDatoUttakNyeRegler` ...
> Korrigere skrivefeil i variabelnavn

- eslint/eslintrc.common.cjs
- package.json
- packages/sak-app/package.json
- packages/v2/gui/README.md
- packages/v2/gui/package.json
- packages/v2/gui/src/sak/meldinger/Messages.tsx
- packages/v2/tsconfig.json
- yarn.lock
**Bakgrunn**
- Ønske om å gradvis kunne skrive om gammal kode til å bli validert med strict typescript sjekking. Så vi får kontroll på null/undefined/any osv.
- Ønske om å kunne skrive ny kode  slik at den blir validert med strict typescript sjekk.
- Ønske om å redusere tal separate, teknisk sett like pakker i prosjektet.
**Resultat**
- Introduserer ny _tsconfig.json_ under _packages/v2/_. Denne vil få effekt på all kode som plasserast under _packages/v2/_ i kjeldekodetreet.
- Introduserer ein ny pakke _@k9-sak-web/gui_. Denne ligger under _packages/v2/gui_. Denne pakken definerer "rå ESM eksporter" i package.json, slik at ein kan styre fleksibelt kva som skal vere tilgjengeleg utanfrå, og konsumenter kan importere direkte frå dei kataloger/moduler det skal vere mulig å importere frå, …
> Tsff 100 v2/ tsconfig og gui package

- packages/utils/src/validation/validators.spec.ts
- packages/utils/src/validation/validators.ts
- packages/utils/src/validation/validatorsHelper.spec.ts
- packages/utils/src/validation/validatorsHelper.ts
- packages/v2/gui/src/utils/validation/regexes.ts
- packages/v2/gui/src/utils/validation/validateTextCharacters.ts
**Bakgrunn**
Behov for å ha validering av gyldige teikn i fritekst felt i v2/.
**Løysing**
Laga ny kode i v2/ der eg forenkla gammal kode til å berre vere ein regex, og returnerer strukturert valideringsresultat.
Bruker deretter ny kode i gammal funksjon.
> Fornya tekstvalideringsfunksjon inn i v2/

- .github/actions/setup-playwright/action.yml
- .github/workflows/deploy-storybook-to-gh-pages.yml
- .github/workflows/storybook-tests.yml
Bakgrunn: Når Playwright caches på branch lager hver PR sin egen cached versjon fordi de ikke deler cache på tvers.
Løsning: Cache Playwright på master
> Skiller installering og caching av Playwright ut i egen action

- packages/fakta-medisinsk-vilkår/src/ui/components/innleggelsesperiodeFormModal/InnleggelsesperiodeFormModal.tsx
Bakgrunn: Dersom bruker taster innleggelsesdatoer på følgende måte `10062024` vil validering mot backend starte før man får tastet `24` i `2024` for til og med dato, altså blir det `100620`, og da vil vi få 400-feil fra backend fordi fra og med dato er i 2024 og til og med blir i 2020.
Løsning: Validerer mot backend i det perioden er ferdig utfylt og fom-dato er samme eller før tom-dato
> Forhindre at validering mot backend gjøres for tidlig

- packages/sak-app/src/behandlingsupport/melding/MeldingIndex.spec.tsx
- packages/sak-app/src/behandlingsupport/melding/MeldingIndex.tsx
- packages/sak-app/src/data/useVisForhandsvisningAvMelding.tsx
- packages/sak-meldinger/src/MeldingerSakIndex.stories.tsx
- packages/sak-meldinger/src/MeldingerSakIndex.tsx
- packages/utils/src/formidlingUtils.tsx
- packages/v2/gui/src/sak/meldinger/Messages.tsx
Flytter oppretting av submitCallback og previewCallback ned til MeldingerSakIndex.
Erstatter dei med ein meir generell onMessageSent callback som kan brukast av både ny og gammal meldingskomponent for å signalisere opp til MeldingIndex at melding er sent.
Reduserer og duplikate props litt.
> Tsff 230 window reload

- .github/workflows/dev-next1-deploy.yml
- .github/workflows/promote-command.yml
- deploy/dev-fss-k9saksbehandling.yml
- deploy/dev-next1.yaml
- deploy/dev.yaml
**Bakgrunn**
Behov for å kunne ha nokre endringer ute til test over litt tid utan å blokkere for at andre endringer kan leggast ut på master og rullast ut til prod.
**Løsning**
Ny branch **dev-next1** oppretta, med tilhøyrande workflow og branch protection rules.
Ved merge til dev-next1 branch frå ei anna branch vil koden der bli bygd og rulla ut til ein separat frontend instans som ellers går mot dei vanlege test backends på samme måte som ved utrulling frå master.
Denne nye instansen har ingress **https://k9-next1.dev.intern.nav.no**
> Dev-next1 branch deployment til k9-next.dev.intern.nav.no

- packages/v2/gui/src/sak/meldinger/FritekstInput.stories.tsx
- packages/v2/gui/src/sak/meldinger/FritekstInput.tsx
- packages/v2/gui/src/sak/meldinger/Messages.tsx
Hadde brukt makslengde verdi frå FritekstbrevinnholdDto server har, men maks lengde er faktisk ulik alt etter om malen som er valgt er av type som større fritekst og tittel, eller berre fritekst.
Endre til å bruke BestillBrevDto makslengde når mal ikkje støtter tittel,og FritekstbrevinnholdDto sin makslengde når mal støtter tittel.
Endre også slik at fritekst prop ikkje blir satt (sendt til server) når det er brev med tittel og tekst, sidan den då vil kunne bli for lang.
> Fiks maks lengde på brevtekst.

- packages/fakta-medlemskap/src/components/oppholdInntektOgPerioder/OppholdINorgeOgAdresserFaktaPanel.jsx
- packages/fakta-utenlandsopphold/src/Utenlandsopphold.spec.tsx
- packages/fakta-utenlandsopphold/src/Utenlandsopphold.tsx
- packages/mocks/mockdata/utenlandsoppholdMock.js
- packages/sak-aktor/src/AktorSakIndex.stories.tsx
Midlertidig løsning mens Storbritannia ligger som EØS-land i kodeverk. Ina har undersøkt og sakene behandles riktig til tross for dette.
> Tsff 641/storbritannia skal ikke vises som eos land

- .github/dependabot.yml
Lar patch og minor oppdateringer gå i samme gruppe.
Legger og opp til ei gruppering for storybook major oppdateringer, men at vanlege går i hovedgruppa.
> Reduser oppdeling av dependabot PRs litt.

- vite.config.js
Når server som er proxied for frontend returnere redirect i location header inneheld den av og til server adressa til proxied server. Dermed sende frontend forespørsel direkte til denne utan å gå via devserver proxy. Dette førte til CORS feil.
Fikser dette ved å i vite dev server omskrive header location returnert frå proxied backend server til å ikkje innehalde server adressa.
> Unngå CORS feil i utviklingsmiljø.

- packages/sak-app/src/behandlingsupport/melding/MeldingIndex.tsx
Bakgrunn:
Ved feil i bakenforliggande system kan det skje at kall til formidling server for å hente maler feiler (returnerer 500). Dette førte til javascript feil sidan MeldingIndex forventa at templates verdi alltid skulle vere eit objekt, og ikkje undefined som det vart viss serverkall feila.
Løysing:
Viser alert med informativ feilmelding istadenfor meldingspanel, viss kall for å hente maler har feila.
Svakhet:
Viss det finnast tilfeller der det er korrekt at det ikkje blir returnert maler for ei sak, så vil det framleis føre til feil. Antar at dette aldri skal skje.
> Unngå javascript feil pga undefined templates i MeldingerSakIndex.tsx.

- packages/v2/gui/src/sak/meldinger/MottakerSelect.tsx
Før dette kunne tidlegare valgt mottaker vise som valgt etter at ein hadde bytte mal, sjølv om komponent state hadde resatt valgt mottaker til å vere første på valgte mal.
> Fiks brevpanel så valgt mottaker viser korrekt etter bytte av mal.

- packages/behandling-utvidet-rett/src/components/UtvidetRettProsess.tsx
- packages/behandling-utvidet-rett/src/panelDefinisjoner/prosessStegUtvidetRettPanelDefinisjoner.tsx
Når status på et panel sjekkes, ser vi først på status på forrige panel. Dersom det ikke er oppfylt avsluttes sjekken. 
Dersom vilkåret ikke finnes i behandlingen fordi saken ble opprettet før denne ble lagt til i backend, vil visningen bli feil i frontend ettersom første panel blir IKKE_VURDERT => alle panel etter vil ignoreres
> Sjekk om aldersvilkår finnes på behandling før panel legges til

- packages/v2/backend/src/k9sak/kodeverk/OpptjeningAktivitetType.ts
- packages/v2/backend/src/k9sak/kodeverk/behandling/FagsakStatus.ts
- packages/v2/gui/src/sak/meldinger/MeldingerBackendClient.ts
**Bakgrunn**
Ny openapi generator på k9-sak setter nullable korrekt på alle properties som teknisk sett kan vere null i java. Altså alle som ikkje eksplisitt er markert med `@NotNull` annotasjon.
**Løysing**
Denne PR legger til `null` som ein mulig type på dei typane der det er nødvendig for kompatibilitet med openapi spesifikasjon generert med ny definisjon frå k9-sak.
> Kompatibiltetsfiks med ny openapi generator

- packages/sak-dokumenter/src/components/DocumentList.tsx
Bakgrunn: Valget for å filtrere dokumentlisten på dokumenter for "denne behandlingen" eller "Alle behandlinger" var ikke synlig om alle dokumentene gjaldt én og samme behandling. Dette virket forvirrende.
Løsning: Viser valget for å filtrere listen uansett.
> Alltid vise filter for dokumentliste

- packages/sak-historikk/i18n/nb_NO.json
- packages/sak-historikk/src/components/maler/historikkMalType3.tsx
Bakgrunn: Ved retur av behandling til saksbehandler mangler tekst i historikkinnslag for aksjonspunktet sykdom.
Løsning: Legger inn manglende tekst.
> Legger inn manglende tekst for historikkinnslag

- packages/behandling-omsorgspenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/OpptjeningPanelDef.tsx
- packages/prosess-vilkar-opptjening-oms/i18n/nb_NO.json
- packages/prosess-vilkar-opptjening-oms/src/components/OpptjeningVilkarAksjonspunktPanel.tsx
- packages/prosess-vilkar-opptjening-oms/src/components/VilkarField.tsx
- packages/prosess-vilkar-overstyring/src/VilkarresultatMedOverstyringProsessIndex.stories.tsx
- packages/prosess-vilkar-overstyring/src/VilkarresultatMedOverstyringProsessIndex.tsx
- packages/prosess-vilkar-overstyring/src/components/VilkarresultatMedOverstyringHeader.tsx
Bakgrunn: 
Når vi ikke har aksjonspunkt for 5089 i behandlingen brukes den generelle VilkarresultatMedOverstyringProsessIndex-komponenten i stedet for OpptjeningProsessIndex. Der får ikke saksbehandler informasjon om vilkåret er oppfylt på grunnlag av §8-47, i stedet står det bare at det er oppfylt.
Løsning: 
Viser når perioder er oppfylt på grunnlag av §8-47
> TSFF-890: Viser når opptjening er løst på grunnlag av §8-47 og vi ikke har aksjonspunkt for 5089 i behandlingen

- packages/prosess-vilkar-overstyring/src/components/VilkarresultatMedOverstyringHeader.spec.tsx
- packages/prosess-vilkar-overstyring/src/components/VilkarresultatMedOverstyringHeader.tsx
Bakgrunn:
Overstyr skal kun være mulig for perioder som er til vurdering i behandlingen. Hvis en skal overstyre tidligere perioder, skal man opprette manuell revurdering.
Løsning:
Skjuler overstyring i inngangsvilkår dersom perioden ikke vurderes i behandlingen
> Overstyring skal kun være mulig for perioder som vurderes i behandlingen

- packages/prosess-uttak/src/ui/components/vurderDato/VurderDatoAksjonspunkt.tsx
Tror at saksbehandler prøver å skrive inn dato på et annet format enn det vi forventet og at dette er årsaken til noen 400-feil på POST til /aksjonspunkt. Aller helst vil de vel skrive ddmmyy og ikke dd.mm.yyyy, så det er sikkert det som skjer her.
> Krever gyldig dato i 9291

- packages/v2/backend/src/shared/jsonSerializerOption.ts
- packages/v2/gui/src/app/K9SakClientContext.tsx
Slik at server serialiserer enum verdier tilsvarande slik openapi spesifikasjon blir generert.
Dette skal føre til at kall der respons inkluderer enum verdier skal fungere korrekt.
> Legger til openapi-compat header på k9-sak typescript klient kall.

- packages/prosess-uttak/src/ui/components/uttaksperiode-liste/UttaksperiodeListe.tsx
Bakgrunn:
Har en liste som splittes i to, og samme useState brukes til å toggle hvilken uttaksperiode som skal ekspanderes fra de to listene. Input er indeks og vil treffe begge listene
Løsning: 
Gjør valgtPeriodeIndex unik
> TSFF-940: uttaksperioder visning toggle periode bug

- packages/sak-meny-ny-behandling/src/MenyNyBehandlingIndex.tsx
- packages/sak-meny-ny-behandling/src/i18n/nb_NO.json
Det viser seg at vi ikke kunne fjerne i18n-opplegget helt enda, siden vi bruker gamle komponenter som krever denne intl-fila for å vise feilmeldinger :( 
Legger den heller tilbake igjen, også får vi migrere over til nye komponenter ved en senere anledning.
> Legg til valideringsmeldinger igjen

- package.json
- packages/rest-api/src/requestApi/RequestRunner.ts
- packages/sak-app/src/bootstrapUng.tsx
- packages/ung/sak-app/app/paths.ts
- packages/ung/sak-app/data/ungsakApi.ts
- scripts/sentry-release-ung.cjs
- ung.html
- ung.vite.config.js
yarn dev:ung starter devserver med ung.html entrypoint og devserver oppsett.
yarn dev:build bygger bundle med ung.html som entrypoint.
Merk at disse framleis bruker /k9/web som base path. Bør endrast til /ung/web.
> Separat ung.vite.config.js for devserver og build av ung-sak-web.

- ung.vite.config.js
Slik at det er samme port som den har i verdikjede.
Fjerner k9 proxy paths som ikkje er tilgjengelege i verdikjede/Q miljø. Slik at det blir lettare å oppdage det som vil feile der.
> Endre devserver port til 9005 for ung-sak-web. Rydd vekk k9 proxy paths

- packages/prosess-uttak/src/ui/components/uttak-detaljer/UttakDetaljer.tsx
Om faktisk og normal arbeidstid blir % fravær vist som NaN (for eksempel ifm. freelancer). Setter vil å vise 0% om prosentutregningen blir NaN
> Vise 0% fravær om faktisk og normal arbeidstid er 0

- packages/v2/backend/src/k9sak/kodeverk/behandling/VilkårType.ts
Bakgrunn: Vilkårtype enum har blitt generert med verdier lik enum name frå backend. Dette var ein feil, skulle blitt generert med kode verdi.
Løysing: For å få kompilert med ny generert klientkode der Vilkårtype er basert på kode verdier må eksisterande bruk av name verdiane endrast til å bli hardkoda.
Når ny generert klientkode er tatt inn i master bør denne også skrivast om til å bruke verdiane derifrå istadenfor hardkoda string verdier som no.
> Fiks Vilkårtype så ny generert backend klientkode blir kompatibel.

- ung.vite.config.js
Fikser portnr i ung.vite.config.js så det stemmer med nytt portnr mot verdikjede. (For lokalt utviklingsmiljø)
> ung-sak portnr blir endra i verdikjede.

- packages/v2/backend/package.json
- packages/v2/gui/src/prosess/ung-vedtak/UngVedtak.tsx
- packages/v2/gui/src/prosess/ung-vedtak/UngVedtakBackendClient.ts
- packages/v2/gui/src/storybook/mocks/FakeUngVedtakBackendApi.ts
- yarn.lock
Generert klientkode var for gammal.
> Fikser slik at kall for brev forhåndsvisning fungerer med generert klient.

- packages/v2/gui/src/prosess/uttak/vurder-overlappende-sak/VurderOverlappendeSak.tsx
Setter tal 0 i init skjema verdi viss det er tilfelle.
> PeriodeMedOverlapp.fastsattUttaksgrad kan vere null.

- packages/behandling-utvidet-rett/src/panelDefinisjoner/prosessStegPaneler/UtvidetRettOmsorgenForMikrofrontendFelles.ts
- packages/behandling-utvidet-rett/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/omsorgenForMikrofrontend/KartleggePropertyTilOmsorgenForMikrofrontendKomponent.ts
- packages/behandling-utvidet-rett/src/panelDefinisjoner/prosessStegPaneler/utvidetRettPanel/utvidetRettMikrofrontend/formateringAvDataTilMikrofrontend/AleneOmOmsorgenObjektTilMikrofrontend.ts
- packages/behandling-utvidet-rett/src/panelDefinisjoner/prosessStegPaneler/utvidetRettPanel/utvidetRettMikrofrontend/formateringAvDataTilMikrofrontend/KroniskSykObjektTilMikrofrontend.ts
- packages/behandling-utvidet-rett/src/panelDefinisjoner/prosessStegPaneler/utvidetRettPanel/utvidetRettMikrofrontend/formateringAvDataTilMikrofrontend/MidlertidigAleneObjektTilMikrofrontend.ts
Bakgrunn: Gammel variant var en funksjon som tok inn mange argumenter, men kan bli vanskelig å lese og fort gjort å sende inn i feil rekkefølge.
Løsning: Sende inn objekt i stedet der man må spesifisere hvert argument med navn.
> Utvidet rett argument fix

- packages/v2/backend/src/k9sak/errorhandling/requestWithExtendedErrorHandler.ts
**Bakgrunn**
Nokre openapi endepunkt definerer query params som er objekt typer. For disse skal query parameter verdier konstruerast ved å destrukturere gitte objekt properties.
**Løysing**
Legger inn midlertidig spesialtilpasning for å få dette til, inntil generert klient er fiksa.
> k9-sak-typescript-client: Fiks destrukturering av objekt som query string parameter.

- packages/v2/backend/package.json
- packages/v2/backend/src/k9sak/generated/metadata.ts
- packages/v2/gui/src/app/K9SakClientContext.tsx
Pga feil i v1 av typescript klient generator har url paths der mangla /api prefiks. Derfor har dette vore lagt til baseUrl ved initialisering av denne i k9-sak.
Feilen i generatoren blir fiksa, og då må initialisering av klient i k9-sak slutte å legge til /api for å unngå feil.
Inkrementerer derfor major versjon av generert api til 2 ved denne endring, og legger inn sjekk på dette ved initialisering av klient i k9-sak.
Den skal då fungere både med v1 og v2 av generert spesifiksjon i ein overgangsperiode.
> base url for generert k9-sak klient endrast for v2 av api-spesifikasjon.

- packages/sak-app/src/behandlingsupport/historikk/HistorikkIndex.stories.tsx
- packages/sak-app/src/behandlingsupport/historikk/HistorikkIndex.tsx
- packages/sak-app/src/behandlingsupport/historikk/v1v2Sammenligningssjekk.tsx
**Bakgrunn**
Samanlikningssjekk for historikkinnslag tekst (v1/v2)  fungerte ikkje heilt, køyrde før alle data var lasta inn, og tok ikkje med full tekst frå v1 innslag viss dei var av type der bruker måtte trykke "utvid" knapp for å vise all tekst.
**Løysing**
Fikser disse problema.
> Historikk v2 feilsjekk

- packages/sak-app/src/fagsakprofile/FagsakProfileIndex.tsx
- packages/v2/gui/src/sak/behandling-velger/BehandlingVelgerK9BackendClient.ts
- packages/v2/gui/src/sak/behandling-velger/BehandlingVelgerSakIndex.stories.tsx
- packages/v2/gui/src/sak/behandling-velger/BehandlingVelgerSakIndex.tsx
- packages/v2/gui/src/storybook/mocks/FakeBehandlingVelgerBackendApi.ts
Da kan man gjøre tilsvarende for ung og pakken blir ikke k9-spesifikk
> Sender ned backend client som prop

- packages/v2/gui/src/prosess/uttak/BehandlingUttakBackendClient.ts
Om hentEgneOverlappendeSaker returnerer med http code 204 No Content, blir resultatet undefined og tanstack tolker det som en feil. Prøver med å returnere null etter råd fra tanstack query issues.
> Return null hvis resultatet er undefined

- loosely-type-checked-files.json
- packages/behandling-ungdomsytelse/src/BehandlingUngdomsytelseIndex.tsx
- packages/v2/gui/src/app/UngSakClientContext.tsx
Tidlegare bug hadde gjenoppstått pga endring i url som gjorde at hardkoda workaround ikkje fungerte lenger.
> Fiks pdf fetch bug ved kall til FormidlingRestTjeneste.

- packages/behandling-omsorgspenger/src/panelDefinisjoner/faktaPaneler/FordelBeregningPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/faktaPaneler/FordelBeregningPanelDef.tsx
- packages/behandling-pleiepenger-sluttfase/src/panelDefinisjoner/faktaPaneler/FordelBeregningPanelDef.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/faktaPaneler/FordelBeregningPanelDef.tsx
Dersom feature toggelen NY_INNTEKT_EGET_PANEL finnes skal fordelingspanelet ikke håndetere aksjonspunkt for ny inntekt. Det skal håndteres i det egne panelet for ny inntekt
> Bruker nytt flagg i faktapanel for å styre om ny inntekt skal håndteres av fordelingspanelet

- packages/sak-app/src/behandlingmenu/BehandlingMenuIndex.tsx
- packages/v2/gui/src/sak/meny/ny-behandling/MenyNyBehandlingIndex.tsx
- packages/v2/gui/src/sak/meny/ny-behandling/components/NyBehandlingModal.tsx
**Bakgrunn**
Oppretting av ny klagebehandling frå v2 NyBehandlingModal.tsx feila pga at ytelsestype ikkje vart sendt med, fordi koden framleis rekna med at denne kom inn som eit kodeverk objekt, medan det er no ein kode string.
> Fix ny behandling modal ytelsetype

- packages/sak-historikk/src/components/maler/HistorikkMalType7.tsx
- packages/sak-historikk/src/components/maler/HistorikkMalType8.tsx
- packages/sak-historikk/src/components/maler/HistorikkmalFelles7og8.tsx
- packages/sak-historikk/src/components/maler/historikkMalType1.tsx
- packages/storybook/stories/mocks/historikkSakV1.ts
- packages/v2/gui/src/sak/historikk/historikkinnslagTsTypeV2.ts
- packages/v2/gui/src/sak/historikk/snakkeboble/Snakkeboble.tsx
url property fjernast frå HistorikkInnslagDokumentLinktDto i k9-tilbake. https://github.com/navikt/fptilbake/pull/2984
Fjerner bruken av property frå k9-sak-web, erstattast med å bruke dokumentId + journalId for key på gui element.
> Fjerner url property frå Historikkinnslag frå k9-tilbake.

- packages/v2/gui/src/fakta/sykdom-og-opplæring/SykdomOgOpplæringBackendClient.ts
- packages/v2/gui/src/fakta/sykdom-og-opplæring/SykdomOgOpplæringQueries.ts
Viss det ikkje er tenkt brukt i framtida foreslår eg å fjerne disse.
Spesielt sidan submitAksjonspunkt ikkje har type på payload er det fort gjort å gjere feil med det.
> Fjerner ubrukt backend kommunikasjon.

- packages/utils/src/beregning/VilkarMapper.tsx
Beregningspanelet fører til teknisk feil i opplæringspenger fordi vurdering av søknadsfrist skjer før initialisering av vilkår. Om man da går inn på beregning klienten kræsje, ettersom beregningsvilkåret er udefinert.
Dette er forøvrig også en feil i pleiepenger, men har nok ikke blitt oppdaget der da man ikke starter i beregningspanelet. Om man manuelt forsøker å gjøre det kræsjer det der, også
> TSFF-1307: Legg til nullsjekk i mapVilkar

- packages/v2/gui/src/shared/vurderingsperiode-navigasjon/PeriodeRad.tsx
Change and compatibility check typescript client-steget i k9-sak gha feiler fordi IKKE_GODKJENT_AUTOMATISK er fjernet i k9-sak, men fortsatt i bruk her
> Fjerner IKKE_GODKJENT_AUTOMATISK da denne er fjernet fra k9-sak

- packages/behandling-felles/src/util/prosessSteg/prosessStegHooks.ts
**Bakgrunn**
PSB viser uttak selv om man får avslag i et av de tidligere panelene. Andre ytelser viser at steget ikke er vurdert. Men vi har data til å vise panelet
**Løsning**
Vise panelet for PILS og OLP også
> Vise uttak selv om man får avslag i tidligere paneler

- packages/sak-historikk/i18n/nb_NO.json
- packages/sak-historikk/src/components/maler/historikkMalType3.tsx
Det ser ut til at spesiell tekstmapping for aksjonspunkt koder (i området 6000 -> 7000) for historikkinnslag av type SAK_RETUR har vore gammel kode frå FP frontend, og ikkje korrekt for k9 sine backend definisjoner.
Endre mapping til å stemme med tekst definert i backend kode.
Av dei med eigen mapping er det kun kode 6003 som er brukt i db, så endre kun denne sidan all denne frontend kode skal slettast snart uansett.
> historikk: Bruk samme aksjonspunkt kode tekstmapping som server har for kode 6003.

- .github/workflows/lint-tscheck-build.yml
- .github/workflows/storybook-tests.yml
- .github/workflows/test.yml
- .github/workflows/valid-pull-request.yml
Github code scanning varsler om at "Workflow does not contain permissions".
Legger til permissions på workflows som mangler det.
> Fiks github code scanning alert

- packages/sak-app/src/behandlingsupport/historikk/v1v2Sammenligningssjekk.tsx
- packages/v2/backend/package.json
- packages/v2/gui/src/kodeverk/mocks/oppslagKodeverkSomObjektK9Sak.ts
- packages/v2/gui/src/sak/totrinnskontroll/TotrinnskontrollSakIndex.stories.tsx
- yarn.lock
Differanser/manglande ord i v2 historikk rapportert gjennom Sentry.
- Justerer historikk v1/v2 samanlikningssjekk basert på undersøkelse av rapporterte differanser, for bestemte historikk innslag typer.
- Fikser feil som gjorde at ignorering av kjende differanser ikkje alltid fungerte.
Fikser ustabil testkode.
> Historikkv2/tsff 1567 

- packages/v2/gui/src/prosess/uttak/uttak-detaljer/GraderingMotArbeidstidDetaljer.tsx
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/GraderingMotInntektDetaljer.tsx
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/UttakDetaljer.tsx
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/UttakUtregning.tsx
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/uttakDetaljer.module.css
- packages/v2/gui/src/prosess/uttak/uttak-detaljer/uttakDetaljer.module.d.css.ts
- packages/v2/gui/src/sak/behandling-velger/components/BehandlingSelected.tsx
- packages/v2/gui/src/shared/aksjonspunktBox/AksjonspunktBox.tsx
Ønsker å unngå bruk av classnames/bind funksjon i v2, slik at vi får typescript sjekk på bruke nav css klassenamn.
Skriver om eksisterande bruk til string interpolering.
> Fjern classnames bind

- packages/v2/gui/src/sak/behandling-velger/components/BehandlingPicker.tsx
https://jira.adeo.no/browse/TSFF-1637
Alle behandlinger vises som Kontroll av inntekt - Må skille behandlingene
Sjekker om det er førstegangsbehandling og bruker ikke visningsnavn dersom det er tilfelle
> TSFF-1637 - Viser ikke visningsnavn dersom førstgangsbehandling

- packages/rest-api/src/axios/getAxiosHttpClientApi.ts
- packages/rest-api/src/xJsonSerializerOptions.ts
- packages/sak-behandling-velger/src/components/BehandlingPicker.tsx
- packages/utils/src/http-utils/axiosHttpUtils.spec.ts
- packages/utils/src/http-utils/axiosHttpUtils.ts
- packages/v2/gui/src/fakta/vurder-nyoppstartet/VurderNyoppstartetIndex.tsx
- packages/v2/gui/src/utils/axios/axiosUtils.spec.ts
- packages/v2/gui/src/utils/axios/axiosUtils.ts
"legacy" frontend kode forventer å få Kodeverdi enums serialisert som objekt frå backend.
Vi ønsker å skrive om backend kode slik at den som standard serialiserer disse til kode string.
"legacy" frontend må be om å få Kodeverdi serialisert som objekt, ved å legge på X-Json-Serializer-Option header på alle requests.
Slik at server serialiserer/deserialiserer Kodeverdi til/frå objekt sjølv om standardinnstilling på server endre seg.
Førebuing til at ung-sak, k9-tilbake og på lengre sikt k9-sak som standard vil bruke @JsonValue/kodeverdi som string serialisering.
> Legg til X-Json-Serializer-Option: kodeverdi-objekt på alle legacy api requests.

- packages/v2/gui/src/prosess/ung-inngangsvilkår/UngInngangsvilkår.stories.tsx
- packages/v2/gui/src/prosess/ung-inngangsvilkår/Ungdomsvilkår.tsx
Inngangsvilkåret for ungdomsytelsen håndterer ikke visning av endret startdato.
https://jira.adeo.no/browse/TSFF-1696
Legger inn håndtering av endret startdato, med tilhørende stories og tester.
> TSFF-1696 - Viser endret startdato i ungdomsytelsen

- packages/v2/gui/src/fakta/sykdom-og-opplæring/4-reisetid/ReisetidIndex.tsx
- packages/v2/gui/src/shared/vurderingsperiode-navigasjon/PeriodeRad.tsx
- packages/v2/gui/src/shared/vurderingsperiode-navigasjon/VurderingsperiodeNavigasjon.tsx
Det ble nevnt på brukertest at det var ønskelig å sortere reisetid med eldste først
Viser reisetid-perioder eldste først
Chevron skal alltid peke til høyre
> TSFF-1591: flipper rekkefølge for reisetid

- packages/v2/gui/src/fakta/sykdom-og-opplæring/1-institusjon/components/InstitusjonDetails.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/1-institusjon/components/InstitusjonFerdigVisning.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/1-institusjon/components/InstitusjonForm.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/1-institusjon/components/InstitusjonVelger.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/2-sykdom/SykdomUperiodisertContainer.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/2-sykdom/SykdomUperiodisertForm.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/NødvendigOpplæringContainer.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/NødvendigOpplæringForm.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/4-reisetid/ReisetidContainer.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/4-reisetid/ReisetidForm.tsx
- packages/v2/gui/src/shared/vurderingsperiode-navigasjon/PeriodeRad.tsx
- Forms ble ikke resatt når man hoppet mellom vurderinger i sykdom og opplæring
- Redigeringsmodus ble ikke togglet av når man hoppet mellom vurderinger i sykdom og opplæring
- "Annen:" skal nå kun vises foran institusjoner som ikke er hentet fra listen over institusjon
- La inn manglende validering på at man har valgt instutsjon fra liste
> Bugfix institusjon#

- packages/v2/backend/package.json
- packages/v2/gui/src/fakta/sykdom-og-opplæring/2-sykdom/SykdomUperiodisertContainer.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/2-sykdom/SykdomUperiodisertForm.tsx
- yarn.lock
Når sykdomsvurdering deles på tvers må alle behandlinger hvor vurderingen er i bruk sjekkes for å bestemme redigerbarhet. Dette gjøres i backend, og resultatet sendes som en felt til frontend
Endre sjekk for å vise redigeringknapp til å ta i bruk det nye feltet
> TSFF-1606: Bruk felt fra backend for å sjekke redigerbarhet

- packages/assets/styles/global.css
- packages/v2/backend/package.json
- packages/v2/gui/src/fakta/sykdom-og-opplæring/1-institusjon/FaktaInstitusjonIndex.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/1-institusjon/components/InstitusjonDetails.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/InstitusjonOgSykdomInfo.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/NødvendigOpplæringContainer.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/NødvendigOpplæringFerdigvisning.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/NødvendigOpplæringForm.stories.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/NødvendigOpplæringForm.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/NødvendigOpplæringIndex.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/components/Avslagsårsak.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/components/DelvisOpplæring.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/3-nødvendig-opplæring/components/InstitusjonOgSykdomInfo.tsx
- packages/v2/gui/src/fakta/sykdom-og-opplæring/FaktaSykdomOgOpplæringIndex.tsx
- packages/v2/gui/src/shared/detailView/DetailView.tsx
- packages/v2/gui/src/shared/labelled-content/LabelledContent.tsx
- packages/v2/gui/src/shared/vurderingsperiode-navigasjon/PeriodeRad.tsx
- packages/v2/lib/src/dateUtils/dateUtils.spec.ts
- packages/v2/lib/src/dateUtils/dateUtils.ts
- packages/v2/lib/src/dateUtils/initializeDate.ts
- yarn.lock
Visuelt delt opp komponenten i dokumentasjon av sykdom og nødvendig opplæring så det blir litt lettere for saksbehandlerne å se skillet.
Er også behov for å kunne gjøre delvise vurderinger på en periode. Altså gi forskjellige vurderinger i en periode som i utgangspunktet er sammenhengende.  
Implementerer klipping av perioder og gjør det mulig å flytte perioder til reisetid. Mye logikk som går på perioder, så er en del nye funksjoner i dateUtils med funksjonalitet som vi har hatt i Period-klassen. Men jeg syns det er fint å kunne bruke de uten å måtte benytte den klassen overalt
> Nødvendig opplæring andreiterasjon

- packages/prosess-avregning/i18n/nb_NO.json
- packages/prosess-avregning/src/components/AvregningPanel.jsx
- packages/prosess-avregning/src/components/AvregningSummary.jsx
- packages/prosess-avregning/src/components/AvregningSummary.spec.tsx
- packages/prosess-avregning/src/components/AvregningTable.spec.tsx
- packages/prosess-avregning/src/components/AvregningTable.tsx
[TSFF-1815](https://jira.adeo.no/browse/TSFF-1815)
Skal ikke vise inntrekk for Ung da det ikke benyttes.
Sjekk på fagsaktype og viser innhold deretter.
> TSFF-1815 - Skjuler inntrekk i simulering for ungdomsytelsen

- packages/behandling-omsorgspenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/OpptjeningPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarFortsPaneler/OpptjeningPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/opplaeringPaneler/InstitusjonPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/opplaeringPaneler/LangvarigSykdomPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/opplaeringPaneler/NødvendigOpplæringPanelDef.tsx
- packages/behandling-pleiepenger-sluttfase/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarFortsPaneler/OpptjeningPanelDef.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarFortsPaneler/OpptjeningPanelDef.tsx
- packages/v2/gui/src/prosess/vilkar-overstyring/VilkarresultatMedOverstyringProsessIndex.tsx
- packages/v2/gui/src/prosess/vilkar-overstyring/components-periodisert/VilkarresultatMedOverstyringHeader.tsx
Bare institusjon som kan gå automatisk, og den kan redigeres i faktapanelet. Vi har ikke behov for å vise overstyringsknapp
vi skjuler overstyring
Fikser visning av tekst for opptjening. Dukker opp som "Behandlingspunkt.Opptjening" nå
> Fjern nøkkkel for overstyring i prosess sykdom og opplæring

- packages/v2/gui/src/sak/meny/ny-behandling/MenyNyBehandlingIndex.tsx
- packages/v2/gui/src/sak/meny/ny-behandling/components/NyBehandlingModal.tsx
uuid ble feilaktig fjernet da ung-sak ikke bruker denne parameteren
legger tilbake uuid som param for oppretting av ny behandling.
> fix - legger tilbake uuid som param for oppretting av ny behandling.

- packages/utils-test/src/intl-test-helper.ts
- packages/utils-test/src/test-utils.tsx
Ved kjøring av tester blir output fra test fylt av mange feilmeldinger om "Missing translation". Tror ingen bruker feilmeldingene til noe og at de bare skaper støy.
Filtrerer ut disse feilmeldingene.
> Filtrerer ut feilmeldinger om "missing translation"

- packages/behandling-felles/src/util/prosessSteg/ProsessStegOverstyringPanelDef.tsx
- packages/behandling-omsorgspenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/AlderPanelDef.tsx
- packages/behandling-omsorgspenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/MedlemskapPanelDef.tsx
- packages/behandling-omsorgspenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/OmsorgenForPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/FortsattMedlemskapProsessStegPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarFortsPaneler/MedlemskapPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/AlderPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/OmsorgenForPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/opplaeringPaneler/InstitusjonPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/opplaeringPaneler/LangvarigSykdomPanelDef.tsx
- packages/behandling-opplaeringspenger/src/panelDefinisjoner/prosessStegPaneler/opplaeringPaneler/NødvendigOpplæringPanelDef.tsx
- packages/behandling-pleiepenger-sluttfase/src/panelDefinisjoner/prosessStegPaneler/FortsattMedlemskapProsessStegPanelDef.tsx
- packages/behandling-pleiepenger-sluttfase/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarFortsPaneler/MedlemskapPanelDef.tsx
- packages/behandling-pleiepenger-sluttfase/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/AlderPanelDef.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/FortsattMedlemskapProsessStegPanelDef.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarFortsPaneler/MedlemskapPanelDef.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/AlderPanelDef.tsx
- packages/behandling-pleiepenger/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/OmsorgenForPanelDef.tsx
- packages/behandling-ungdomsytelse/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/AlderPanelDef.tsx
- packages/behandling-ungdomsytelse/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/UngdomsprogramPanelDef.tsx
- packages/behandling-unntak/src/panelDefinisjoner/prosessStegPaneler/inngangsvilkarPaneler/MedlemskapPanelDef.tsx
https://jira.adeo.no/browse/FAGSYSTEM-396943
I noen tilfeller fikk ikke overstyringspanelet props som er konvertert med kodeverkendringer
Fikser det ett sted for alle.
> FAGSYSTEM-396943 - Retter props for overstyringspanel

- packages/prosess-vedtak/src/components/revurdering/VedtakInnvilgetRevurderingPanel.tsx
Vi må vise at opplæringspenger er innvilget i revurdering
Vi viser at opplæringspenger er innvilget i revurdering
Fjerner sjekk på ytelse. Dette vil vi vel alltid vise?
> TSFF-1975: viser innvilget resultat i vedtak i revurderinger

- packages/v2/gui/src/prosess/ung-beregning/ArbeidOgInntekt.tsx
https://jira.adeo.no/browse/TSFF-1958
Vi sender ned alle perioder til vurdering, uavhengig av om de har avvik. Backend forventer kun perioder med avvik.
Filtrerer ut og sender kun ned perioder med avvik.
> TSFF-1958 - filtrer perioder med avvik

- packages/v2/gui/src/sak/dekoratør/HeaderWithErrorPanel.tsx
Vi lenker til LOS for Ung men Ung skal ikke brukes LOS.
Lenker ikke til LOS dersom man er i Ung
> Retter lenke i header for ung

- packages/ung/sak-app/behandlingsupport/BehandlingSupportIndex.spec.tsx
- packages/ung/sak-app/behandlingsupport/BehandlingSupportIndex.tsx
https://jira.adeo.no/browse/TSFF-2066
Beslutter havner ikke i beslutterpanelet automatisk.
Venter til rettigheter er hentet før hjelpepaneler vises. Fører til riktig navigasjon.
> TSFF-2066 - venter til behandlingrettigheter er hentet før tabs vises
